### ISSUE TITLE
Improvement: Add current and total time in song slider

### ISSUE THREAD

**Issue by Daniel-at-github** [SimpleMobileTools/Simple-Music-Player#1]
Improvement: Add current and total time in song slider
Use case: Begin to listen podcast in PC and trying to continue in Simple-Music-Player in the same second of the podcast that I left it.

**Comment by tibbi** [comment]
thanks for the report, it will be fixed with 1.9 which should be downloadable soon. Displaying the numeric progress will be disabled by default as I think most people wont need it, but it can be easily enabled in About -> Settings.

**Comment by Daniel-at-github** [comment]
Thanks. I will wait for the version 1.9 to appear in https://f-droid.org/repository/browse/?fdid=com.simplemobiletools.musicplayer

**Comment by tibbi** [comment]
okay, hopefully they will update it and add the rest of the apps soon. My pull request is there for 3 days already, they just have to accept it.
