### ISSUE TITLE
Plugging in/out earphones have delay.

### ISSUE THREAD

**Issue by nulledone** [SimpleMobileTools/Simple-Music-Player#109]
Audio won't transfer to earphone immediately, and instead it continues to play few seconds over speaker while plugged in.

When earphones unplugged while playing a song, makes a little noise(20ms~ of current track maybe) over speakers.

**Comment by tibbi** [comment]
these things are handled by the system, not me

**Comment by nulledone** [comment]
That's weird, because no other app is having this behavior.
