### ISSUE TITLE
Slow F-Droid updates

### ISSUE THREAD

**Issue by stelariusinfinitek** [SimpleMobileTools/Simple-Music-Player#11]
I know this doesn't depend on you. I'm waiting for so long for some updates, the player is still at version 1.12, I can't test it. Can you release an apk with every release? That would make things easier.

**Comment by tibbi** [comment]
indeed they are releasing new versions, I just have to create a Release https://github.com/SimpleMobileTools/Simple-Music-Player/releases on github, their daily script will catch it and update it. I forgot to create the 1.13 tag, so its taking longer now :) Ill just have to pay more attention in the future. I usually build a new version with every change already.
