### ISSUE TITLE
Sort by track number

### ISSUE THREAD

**Issue by olmokramer** [SimpleMobileTools/Simple-Music-Player#123]
I mostly listen to single album playlists, so it would be nice to be able to sort by track number without having to set the "show filename as song title" to "always".

Nice music player, appreciate the lack of advance features!

**Comment by tibbi** [comment]
it will be added someday, it is already reported at #111

**Comment by olmokramer** [comment]
Ah ok, in that case I misunderstood that issue title. Thanks!
