### ISSUE TITLE
instead of next/prev track, add option to skip -20 +20 sec

### ISSUE THREAD

**Issue by jpritikin** [SimpleMobileTools/Simple-Music-Player#125]
When listening to podcasts instead of music, I'd prefer if the buttons skipped minus or plus 20 seconds instead of prev/next track.

**Comment by tibbi** [comment]
You can already skip forward/backward by pressing the current or total time. Currently there is no minimal skip duration, so at short tracks it might not work well. It will be updated in the next version.
