### ISSUE TITLE
sometimes loses bookmark of what was playing

### ISSUE THREAD

**Issue by jpritikin** [SimpleMobileTools/Simple-Music-Player#126]
I'm not sure when this happens but the player sometimes seems to forget which is the current track. This is really bad for podcasts. I suggest the current bookmark be stored in duplicated and backed up so that the player never gets confused.

**Comment by tibbi** [comment]
What do you mean by forgetting? If you close the app and you open it the next time it is reset? That is the expected behaviour currently, saving last track is not implemented.

**Comment by jpritikin** [comment]
Oh! Then make it a wish list item.

**Comment by mrvanes** [comment]
I would like to add that not only remembering the last track, but also time in track would be nice. I tend to listen to long DJ mixes a lot, which I would like to pick-up where I left.

**Comment by vinibali** [comment]
Hello there,
can we expedite this feature request?
I'd like to use a lightweight music player. This should be a must-have feature.
Regards

**Comment by tibbi** [comment]
this should be solved already after the rewrite from 5.4.+
