### ISSUE TITLE
Support for more audio file formats

### ISSUE THREAD

**Issue by despens** [SimpleMobileTools/Simple-Music-Player#136]
Hello, I really like the Simple Music Player!

What I am missing is support for more audio file formats. Lots of my music is in OGG, M4A or FLAC format, and these files are not picked up by the player, just the MP3 ones. Or maybe I am doing something wrong?

**Comment by despens** [comment]
Sorry, missed that the player doesn't auto-update when contents of a directory change. I guess that would be the real feature request then :smile:!

**Comment by tibbi** [comment]
ye, but that is already reported :)
