### ISSUE TITLE
SMP cannot cope with large music collection - freezes

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/Simple-Music-Player#138]
Nokia 6 with Android 7.1.2.

My music collection is about 2000 songs, 14GB data. It is a mix of mp3, ogg, flac and art data. Data is organized in folders starting from one rootfolder on the SDcard.
Simple Music Player freezes upon many actions. e.g. adding the rootfolder to the playlist, opening the All Song playlist, going back from settings to normal view. Then I get "the app is not responding" notification every few minutes. It can take 10min to 15min before the app responds again.

Also likely related is that many songs are processed then displayed with < unknown > artist while the information is available in the file meta data. When I re-install the app (to start with an empty playlist) and only add one folder it is fine.

![screenshot_20180312-004622](https://user-images.githubusercontent.com/38086529/38393090-092f408a-392a-11e8-829f-75eaef3a4f3a.png)
![screenshot_20180312-004614](https://user-images.githubusercontent.com/38086529/38393095-0e072960-392a-11e8-8e05-0d31b762cd08.png)

Reference: VLC player on this phone displays a progress bar when scanning for all media in the same folders, it takes a few minutes but does not hang. Also VLC can recognize all meta data like Artist properly.

**Comment by GuitarBilly** [comment]
Nokia6 on Android 7.1.2 with Simple Music Player (SMP) version 3.2.5

Additional information : behavior with only 100 songs from 10 albums in one playlist:
At startup i have to accept Wait for 2x at "SMP app does not respond" before the UI appears. I think the app is processing the playlist again upon each start as sometimes the song meta data is not displayed correctly as you can see from the previous screenshots (filename + <unknown> instead of Title + Artist)

VLC works fine on this phone with ~2000 songs from dozens of albums including all used by SMP.

**Comment by tibbi** [comment]
it should be improved in version 4.0.0, the way songs are stored will be completely rewritten.

**Comment by tibbi** [comment]
are you sure the metadata in the actual files is set properly? I dont see how could the app retrieve it wrong.

**Comment by GuitarBilly** [comment]
yes, if i use SMP or VLC to show the information about artist/title is correct, refer to the posted screenshot of the Cream song for example. 

Being 'dumb computer code' i would expect SMP to process folder after folder, song by song. So now i have cleared the app data and cache, removed it, re-installed it and added my collection again. Lets wait and see.

**Comment by tibbi** [comment]
I havent really tested importing folders containing other folders, but Im not sure how could that break anything. Ill take a look at it someday.

**Comment by GuitarBilly** [comment]
My only conclusion now is that importing one folder or a collection of folders up to 100 songs goes fine. When selecting 300 songs or more when adding a map it is guaranteed to go wrong with the displayed title/artist from that data.

Is it a lot of work to run the app with a verbose log??

**Comment by tibbi** [comment]
I dont really have any logs in the apps so it wouldnt help. I can try reproducing it.

**Comment by tibbi** [comment]
should be better already since the big rewrite

**Comment by GuitarBilly** [comment]
v5.4.4
dear tibbi,
sorry to report but I have stopped using SMP as main player because already a few versions ago my existing long playlist was wiped out after an app update. 
No problem, if things are improved i can try to import my songs again...

However at the moment i cannot get any folder with songs from the SDCARD to be imported as a playlist. I have tried different methods, and also removing the app storage and cache so it asks me again for permissions etc. 


1. main screen, select playlist tab, create playlist, click the playlist, click "add map to playlist", browse to a folder and select, after a little while it asks to give the playlist a name, then the playlist is created but with 0 songs, even after some time nothing changes. ( waited > 10mins, tried different folders with < 20 songs, both mp3 and ogg format)

2. main screen, select playlist tab, go to menu, select "create playlist from this map", browse to a folder, after a little while it asks to give the playlist a name, then the playlist is created but with 0 songs, even after some time nothing changes. ( waited > 10mins, tried different folders with < 20 songs, both mp3 and ogg format)

3. main screen, select playlist tab, create new playlist, click the playlist, click "add file to playlist", browse to a folder and select one song, it displays "unknown error has occurred".


The main thing seems to be that my songs are all on the SDCARD. So i copied one folder to the internal memory and i can import that without any issue.

In the past it was only slow to add a lot of new songs. Once added to a playlist there were never any issues to play the songs and display cover art from SDCARD.
Unfortunately i cannot remember exactly which version wiped the playlist ! It is at least a few versions and several months ago, could be longer. I am not sure if the version that wiped the playlist is the rootcause for the SDCARD issue, as i did not add a folder to a playlist for a long time; that function could have been broken before? You should be better to judge that than me.


p.s. Next to that i also noticed that forcing the app to use english language does not work ( i wanted to enable it to write the exact english strings since i have the app in my native language ).

**Comment by GuitarBilly** [comment]
Upon reading more closely, it could be related to reported #280 or #282 or #266 ?
I will clear all data/cache from SMP and start over by adding one folder to a playlist and leave the app running on the phone for a day or so.

**Comment by GuitarBilly** [comment]
hello @tibbi,
you probably do not get triggered without the @ mention? 
FYI - Even leaving the app open for days does not load any music from the SDcard for me (one folder selected).

v5.5.2 on Andriod 7.1.2

This means that for now i stop using the SMP as my collection (15GB) is too big to add on the internal memory.
Meanwhile i have reverted to use VLC.

**Comment by tibbi** [comment]
I did read the previous too. Many performance and other improvements will be added in 5.6.0 released soon, retry it once available.
