### ISSUE TITLE
Exclude folders or specify folders

### ISSUE THREAD

**Issue by natrius** [SimpleMobileTools/Simple-Music-Player#140]
**Cellphone:** 
OnePlus 3

**OS:** 
LineageOS 15.1

**App version:** 
3.2.5 (F-Droid)

I have a different folder on the internal storage for audiobooks and another player (Voice) so i don't want the audiobooks to appear in the player.
In the simple gallery there are options to exclude or hide folders, implement something like that in the music player too. 
That would be amazing, because the built-in music player in lineageos does not work at all :D

If you need further information, just ask.

**Comment by tibbi** [comment]
I dont plan adding folder exclusion, that would make it even more complicated. Better just create a new playlist from the folders you want in there.

**Comment by natrius** [comment]
I found that i can add folders via adding playlists. Sorry about that.
Maybe add the option to add folders directly when adding a new playlist, as option?
Otherwise, thanks. My fault.

**Comment by tibbi** [comment]
Playlist creation and editing needs more tweaks, I dont really like the current way of doing it.
