### ISSUE TITLE
AAC files only appear in "All songs" playlist

### ISSUE THREAD

**Issue by pikim** [SimpleMobileTools/Simple-Music-Player#144]
In any other playlist AAC files don't show up and therefore can't be played. But in "all songs" they play nicely.

**Comment by tibbi** [comment]
you mean if you use the "Add file/folder to playlist", it isnt added?

**Comment by pikim** [comment]
That's correct. AAC files aren't added at all. Let's assume the following structure:
```
Music
+-- Songs
    +-- song1.mp3
    +-- song2.aac
    +-- song3.m4a
```
In playlist "all songs" all 3 three show up and can be played. In playlist "Songs" I created from the subfolder the AAC file doesn't show up.
