### ISSUE TITLE
Bug: playback queue after file delete

### ISSUE THREAD

**Issue by Vodochnik** [SimpleMobileTools/Simple-Music-Player#152]
Hi,
i was looking for a player with simple feature: 1 big button to delete current song from storage without confirmation and such. Nothing on market.

How to reproduce a bug in SMP: 
1) load some songs, song1 - song9
2) delete from storage, say, 2nd song (song2). It diappears and song3 starts. All ok.
3) now delete song3. It disappears and song**5** starts.

I think, intent NEXT is raised, but queue is not refreshed.
if (song == MusicService.mCurrSong) {
                    activity.sendIntent(NEXT)
                }

P.S. no player on the market supports custom buttons on playback screen (i have found nothing).
Black player EX supports action on double click on cover picture, including delete current song (almost what i need) but with confirmation. Closed source.

**Comment by Vodochnik** [comment]
Sorry, but it does not fix the issue, just take a look (screencast with Song1-Song9) https://youtu.be/PY2KOVRtxhw

**Comment by tibbi** [comment]
should be solved already since the big rewrite
