### ISSUE TITLE
Facing this problem when running app

### ISSUE THREAD

**Issue by SK010101** [SimpleMobileTools/Simple-Music-Player#153]
![2018-07-14](https://user-images.githubusercontent.com/41238359/42726308-e5f57c0e-87af-11e8-9371-b66e5396cd9c.png)

**Comment by tibbi** [comment]
because you updated the Commons library to the latest version. I will update it when Ill be working on it.

**Comment by SK010101** [comment]
thnx sir, but after fixing this and running it, it shows toast message this is fake app. Can you please find me a way to remove that.
