### ISSUE TITLE
jump to song currently playing

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/Simple-Music-Player#158]
Feature request. 
The possibility to jump the playlist view to the song that is currently playing.

At the moment i have to scroll manually to the song that is playing. It is also shown in the top, but many times i want to explore the other songs of the album or artist.
My playlist is > 1000 songs so scrolling and finding the play indicator (music note) is not easy.

It could be implemented by double tapping on the Song Title / Artist at the top of the playlist? This should move the songlist/playlist such that the song that is currently playing is back in view.

Another implementation could be continously updating the view such that the current song playing is always in view.

SMP v4.1.1

**Comment by rlv-dan** [comment]
Yes, automatically jumping to the currently playing song would be very welcome! With 2000 in my playlist it's just impossible to find the current playing song.

**Comment by tibbi** [comment]
the UI has been changed since then already
