### ISSUE TITLE
didn't play everything after reinstall

### ISSUE THREAD

**Issue by ankek** [SimpleMobileTools/Simple-Music-Player#159]
I have reinstalled app and see the song list but then I pushed play button nothing going on. Just 00:00 at timecount and playback is freezing.
Android 7.1.1

**Comment by tibbi** [comment]
so it was working fine previously?

**Comment by ankek** [comment]
Hi Tabor,


Thank you for your application.


Yes, everything works fine until I reinstalled app. How can I help you with that trouble?




Yours truly Anton Kekkonen







От: Tibor Kaputa


Отправлено: четверг, 2 августа, 9:24


Тема: Re: [SimpleMobileTools/Simple-Music-Player] didn't play everything after reinstall (#159)


Кому: SimpleMobileTools/Simple-Music-Player


Копия: ankek, Author






so it was working fine previously?

**Comment by ankek** [comment]
It looks like this.













Yours truly Anton Kekkonen







On Thu, Aug 2, 2018 at 9:24 AM +0300, "Tibor Kaputa" <notifications@github.com> wrote:












so it was working fine previously?

**Comment by tibbi** [comment]
what app version do you have?

**Comment by ankek** [comment]
4.1.1 latest at f-droid market

**Comment by ankek** [comment]
Hi there, the trouble in f-droid, I have successfully installed app from play store

**Comment by tibbi** [comment]
then the full reinstall fixed it probably. The f-droid version is the same as on playstore.
