### ISSUE TITLE
Request: update widget according to current state

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [SimpleMobileTools/Simple-Music-Player#162]
Currently, not only it doesn't show song information (name, photo,etc...), but its "play" button doesn't get updated to "pause" button.

**Comment by tibbi** [comment]
it should obviously work. Dont you have all widgets stuck? Try restarting your device. Also, what app version and Android OS version do you have?

**Comment by AndroidDeveloperLB** [comment]
How odd. Maybe I had an old version.
Now it works fine.
Closing the issue.

**Comment by AndroidDeveloperLB** [comment]
Oh wait. This bug came back.
I don't get when it occurs.
Look:

![image](https://user-images.githubusercontent.com/5357526/44998700-3a360300-afc0-11e8-8a65-21288d245ffe.png)

And on video, you can see I try to click on the "play" button, and nothing occurs. Later I press on the widget itself, and then it gets to know the songs again (and then it really plays, including notification), but still the widget won't get updated.

[device-2018-09-03-214509.zip](https://github.com/SimpleMobileTools/Simple-Music-Player/files/2346370/device-2018-09-03-214509.zip)

**Comment by tibbi** [comment]
should be fixed in 5.2.2 released soon, reopen if not
