### ISSUE TITLE
Cannot control from lockscreen

### ISSUE THREAD

**Issue by mraandtux** [SimpleMobileTools/Simple-Music-Player#164]
Android version: 8.1 (w/ MIUI 8.5.26)
![screenshot_2018-09-13-15-02-08-994_lockscreen](https://user-images.githubusercontent.com/2002796/45472256-40697380-b766-11e8-9fb1-4def2e6d0330.png)

**Comment by mraandtux** [comment]
@tibbi nope, just Simple Music Player (see the icon on upper left) .

**Comment by tibbi** [comment]
that is not my UI, dont you have some other music player running in the background? Check your Recent apps.

**Comment by mraandtux** [comment]
@tibbi nope either. But @AdrienPoupa 's Vinyl Music Player can be controlled and load the metadata from the lockscreen.

**Comment by tibbi** [comment]
should be working already
