### ISSUE TITLE
Title, artist, album and progess not shown over Bluetooth

### ISSUE THREAD

**Issue by hvhaugwitz** [SimpleMobileTools/Simple-Music-Player#169]
When playing music with the Simple Music Player over Bluetooth in my car the track information (such as title, artist, album and progress) are not shown on the vehicles display. This works with other apps (eg AntennaPod[0]).

[0] https://github.com/AntennaPod/AntennaPod

**Comment by tibbi** [comment]
does it still happen with the latest version?

**Comment by jeancf** [comment]
I have the same issue with my car. I don't know if it is related but the widget on the lock screen of the phone also shows "unknown" instead of the title of the song and the navigation keys so not work.

**Comment by tibbi** [comment]
that is already an extension of this bug, Im going step by step :)
