### ISSUE TITLE
Bluetooth headset

### ISSUE THREAD

**Issue by kloevchen** [SimpleMobileTools/Simple-Music-Player#17]
Thank you for the app. That's what I searched. Immediately shufling.
But I can't choose the next track on my headset. Can you make it possible?

**Comment by Zykino** [comment]
I would appreciate this too so I don't have to touch my phone while I'm driving. (Means even if the app is good on phone I installed VLC too).

I don't know if it's in the same "bug/feature" or not but I cannot use my OnePlus 3 gestures to Play/Pause or use next/previous track. I'm use to draw || or < or > on my screen without looking at it and This app doesn't register the commands. (Should I open an other issue for that?)

**Comment by tibbi** [comment]
ye thats a whole different issue, create another ticket please.
