### ISSUE TITLE
Request: Please Create Album List

### ISSUE THREAD

**Issue by 0pLuS0** [SimpleMobileTools/Simple-Music-Player#191]
Hello,

First I want to say I love what you are doing so far!

But with hundreds of songs and hundreds of albums this is just to insane to use!

So I have, hopefully a simple request you can fill and improve this app.

I'm all for simplicity, but can you please make a ```Album``` section so you can view the music based on Albums, which is going to make it a lot easier to scroll through, instead of all just names presented as it is now.

Then tap on an Album, go to a Track list, tap a song and play... Simple :+1: 

Here are some screen shots I've attached of what I am talking about.

Thank you very much for your consideration, I hope you will do this, and it will be really great!

```HAPPY HOLIDAYS & HAPPY NEW YEAR!```

```ALBUMS```
![simple_1](https://user-images.githubusercontent.com/36190223/50391470-70e58400-073d-11e9-86ec-92eb524c2eef.jpg)

```TRACKS```
![simple_2](https://user-images.githubusercontent.com/36190223/50391472-76db6500-073d-11e9-9bdf-a84e3bcbcca4.jpg)

**Comment by papjul** [comment]
Seconding this.

I'm extending the request a little, and propose a solution below to make it more generic.

You can get inspired by LineageOS' Eleven music player. There are three tabs: Titles (current list), Artists and Albums.

It consists in grouping titles according to one ID3tag:
- Artists: artist or artist of the album > on click > list all titles with this ID3tag
- Albums: album > on click > list all titles with this ID3tag

And that's it to keep it simple.

To push it further, you could also create customized tabs for users wanting to extend the possibilities from the settings such as:
- Genres: genre > on click > list all titles with this ID3tag
- Stars: star (not starred, 1, 2, 3, 4 or 5 stars) > on click > list all titles with this ID3tag
- Decade: year (grouped by decade for example) > on click > list all titles with this ID3tag

**Comment by tibbi** [comment]
it has been added in 5.4.0
