### ISSUE TITLE
Buttons in the player view have no labels (contentDescription).

### ISSUE THREAD

**Issue by p-f** [SimpleMobileTools/Simple-Music-Player#192]
The buttons in the player to select the previous or next title apparently don't have a label.
I was trying to use this player with a phone using talkback (which reads out contents on the screen for visually impaired people) and when I selected those buttons it just said "Button" and some number.
Is it possible to set a label or a description on those keys to make this app more usable for blind/visually impaired people?

I can have a look and provide a PR, if you accept those.

**Comment by tibbi** [comment]
I do accept them, the "contentDescription" field is used there. In case you add a new string please add it to all language files. Thanks
