### ISSUE TITLE
ERROR: Failed to resolve: com.github.kabouzeid:AndroidSlidingUpPanel:3.3.0-kmod3

### ISSUE THREAD

**Issue by mpt212** [SimpleMobileTools/Simple-Music-Player#197]

**Comment by 09388222808** [comment]
ERROR: Failed to resolve: com.github.kabouzeid:AndroidSlidingUpPanel:3.3.0-kmod3
Hello, please help me to fix this error

**Comment by DaveAAA** [comment]
Change it to:
implementation 'com.sothree.slidinguppanel:library:3.3.1'

It should probably work
