### ISSUE TITLE
Request: store paused position when close

### ISSUE THREAD

**Issue by MaDill** [SimpleMobileTools/Simple-Music-Player#198]
It would be nice if the app can store the last play position. I use it often to play long podcasts and when I pause the playback to do something else and after some tim come back to the program the last play position is gone and I have to find the position again.

**Comment by PaperMountainStudio** [comment]
I agree. This is what I miss the most.

**Comment by tibbi** [comment]
this should be solved already after the rewrite from 5.4.+
