### ISSUE TITLE
change default theme in code

### ISSUE THREAD

**Issue by CoderoidAcademy** [SimpleMobileTools/Simple-Music-Player#206]
hi, how i can change default theme
i means how set light theme to default theme of this source in code?
What should I change in code?

**Comment by tibbi** [comment]
you can change it in Commons, but using the library in other apps is not advised, I dont give support for it.

**Comment by CoderoidAcademy** [comment]
i have your commons project and sync it by Simple Music Player.
What should I change?
What class or method of commons?
