### ISSUE TITLE
jump +5/-5 sec 

### ISSUE THREAD

**Issue by stickydrive** [SimpleMobileTools/Simple-Music-Player#212]
I'd like to suggest an small feature, Since I'm using this app mostly to play podcasts which I download in advance.
It would be cool if you could add  a jump +5/-5 sec buttons ( Like Netflix Player).

thanks for reading it.

**Comment by tibbi** [comment]
clicking on the current or max duration will skip by 10s from version 5.3.0, thats how it works in all our apps with some audio/video player
