### ISSUE TITLE
Feature Req: pull to rebuild playlist gesture

### ISSUE THREAD

**Issue by stickydrive** [SimpleMobileTools/Simple-Music-Player#216]
It would be nice to have an pull down gesture, (swipe down to refresh in your other apps) to rebuild the playlist in case new songs are added, to the same folder.

**Comment by tibbi** [comment]
the UI has been changed already

**Comment by SomeoneIsWorking** [comment]
I can't find any option to refresh the library and pull down doesn't trigger a refresh

**Comment by jcentel** [comment]
Me too. Playlists created from folders don't realize about folder changes.
