### ISSUE TITLE
Add online music and language option to simple music player app

### ISSUE THREAD

**Issue by pzdawood** [SimpleMobileTools/Simple-Music-Player#217]
***proposal***
My suggestion is to app the online music botton which will lead to listen music online without download it and language option so that anyone can use this app through out the world.
***Examples***
After adding online music botton the app looks like this 
![PicsArt_07-11-10 36 43](https://user-images.githubusercontent.com/38599784/61070870-446d2d00-a42d-11e9-8e33-e5cdb4ce117f.png)
After adding language app the app looks like this
![PicsArt_07-11-10 00 12](https://user-images.githubusercontent.com/38599784/61070917-61a1fb80-a42d-11e9-8617-8dc0033f18fb.png)
***Benefits after adding these features***
1.The benefit of adding online music botton is that the user can search and song from the app and listen without download the song if the user loves the sing he can also download the song from this app. The user can listen the song without wasting their storage.
2.The benefit of adding language option is that Now by implementing Language feature, user can use the app in many languages. As we all know that there are many languages in this globe and many user are not comfortable with english language. So this feature can help user to feel comfort with his mother language.so any one from any contry can use this app without facing any language problem.

**Comment by tibbi** [comment]
all apps are offline, so dont expect having any online playback

**Comment by pzdawood** [comment]
What about language sir

**Comment by tibbi** [comment]
if a device has an other language set, not english, there is already a "Use english" checkbox appearing. Selecting custom language isnt on the roadmap for now. Anyway, it affects all apps, not only the music player. And try reporting one thing per issue in the future, it is easier for handling. Thanks
