### ISSUE TITLE
Don't ignore exceptions

### ISSUE THREAD

**Issue by recheej** [SimpleMobileTools/Simple-Music-Player#218]
I took a look through some of the code and noticed that in most places, exceptions are ignored. Not sure if you're a professional developer, but that is pretty bad practice! At the very least you should log the errors somewhere. (crashlytics maybe?). Anyways. good luck!

**Comment by tibbi** [comment]
the app is offline so no, I cannot log it anywhere

**Comment by recheej** [comment]
Maybe you can store logs offline and allow the user to email the log to you if they have issues?

**Comment by tibbi** [comment]
I dont plan doing that, such logs usually dont help
