### ISSUE TITLE
play OGG format

### ISSUE THREAD

**Issue by vinibali** [SimpleMobileTools/Simple-Music-Player#228]
Hi!

My phone couldn't play OGG files. The app is able to find them in a defined directory, can recognize it's length, but when I touch the play button it just simply doesn't run.
Simple Music Player 5.2.4 from Fdroid
Nitrogen OS (Android 10)
OnePlus 3
If there is any way how I can help you in the debugging, just let me know.

Regards

**Comment by vinibali** [comment]
Sorry, I forgot to mention the file details.
`Vorbis Version                  : 0
Audio Channels                  : 1
Sample Rate                     : 8000
Nominal Bitrate                 : 22.4 kbps
Vendor                          : Xiph.Org libVorbis I 20101101 (Schaufenugget)
Comment                         : Processed by SoX
Duration                        : 1:57:06 (approx)`

**Comment by tibbi** [comment]
that is almost 2 hours long? Can you try some shorter sample, maybe send me a short sample file?

**Comment by vinibali** [comment]
It's pretty same with a smaller file, which I've uploaded here:
[free music sample](https://drive.google.com/file/d/1o6Te_zKd9keCSjcoQX94SAce6BrO4Nrc/view?usp=sharing)
In the meanwhile, I checked the codecs on the phone with Aida64:
c2.android.vorbis.decoder: audio/vorbis
OMX.google.vorbis.decoder: audio/vorbis

**Comment by tibbi** [comment]
It plays just fine on both my Android 9 and 10 devices, I guess the issue is caused by your custom ROM. I dont really care about codecs or any of these things you listed, I just tell the system to play the song. Does it work for you in other downloaded apps?

**Comment by vinibali** [comment]
Other lightweight players (Music Player GO, Phonograph) are the same, but mpv and Poweramp is able to play them.
I'll report it on the ROM's page, can we let this ticket open for a while?

**Comment by vinibali** [comment]
I had to disable vorbis compressed offload at /system/vendor/etc/audio_policy_configuration.xml.
You can close this ticket, thank you!
