### ISSUE TITLE
App shows filenames rather than "Title"/"songname" (TIT2) tag values for song names.

### ISSUE THREAD

**Issue by jaimet** [SimpleMobileTools/Simple-Music-Player#238]
Hi.

This is not (yet) a bug report - it is a question.

I use [beets](https://beets.io/) to tag all my music with Musicbrainz metadata, so the correct name for each song is stored in the relevant [id3 tag](https://en.wikipedia.org/wiki/ID3#ID3v2_frame_specification) (key=TIT2).

Simple Music Player, however, is displaying my songs' filenames rather than the values of these tags.

Could you please let me know whether this is a bug, or is this "by design"?

Thanks.

**Comment by tibbi** [comment]
it should check file exif for title, try sending a sample file for testing

**Comment by jaimet** [comment]
I have just tried to reproduce my issue but Simple Music Player is now working correctly (i.e. I can **not** reproduce my issue).

I have attached a test file in case it is useful for anyone in the future (and that includes me!). The test file is [this "sound example"](http://ccrma.stanford.edu/~jos/mp3/pno-cs.mp3) (which is linked to from [this page](https://ccrma.stanford.edu/~jos/waveguide/Sound_Examples.html)) which I have then tagged (using [beets](https://beets.io/)) **as though it was** [Track 1 (The "Vivace") from Rachmaninov's Piano Concerto no. 1 in F-sharp minor](https://musicbrainz.org/release/1677c481-82f5-4168-9c6e-6926078c2d19/disc/1#161c15af-4b91-3414-a959-4a749d7140d9). As github will not allow files with the extension .mp3 as attachments to issues, I have zipped it up - the original filename is `pno-cs.mp3`.

beets inserts the following tags into the file:

```
$ mid3v2 -l pno-cs.mp3 
IDv2 tag info for pno-cs.mp3
TALB=The Four Piano Concertos
TBPM=0
TCMP=0
TDOR=1988-08
TDRC=1988-08
TIT2=Piano Concerto no. 1 in F-sharp minor, op. 1: I. Vivace
TLAN=eng
TMED=CD
TPE1=Sergei Rachmaninoff
TPE2=Sergei Rachmaninoff; Vladimir Ashkenazy, Royal Concertgebouw Orchestra, Bernard Haitink
TPOS=1/2
TPUB=Decca Records
TRCK=1/12
TSOP=Rachmaninoff, Sergei
TXXX=ALBUMARTISTSORT=Rachmaninoff, Sergei; Ashkenazy, Vladimir, Royal Concertgebouw Orchestra, Haitink, Bernard
TXXX=ASIN=B0000041UM
TXXX=Album Artist Credit=Rachmaninov; Vladimir Ashkenazy, Concertgebouw Orchestra, Bernard Haitink
TXXX=Artist Credit=Sergei Rachmaninov
TXXX=CATALOGNUMBER=421 590-2
TXXX=MusicBrainz Album Artist Id=44b16e44-da77-4580-b851-0d765904573e
TXXX=MusicBrainz Album Id=1677c481-82f5-4168-9c6e-6926078c2d19
TXXX=MusicBrainz Album Release Country=XW
TXXX=MusicBrainz Album Status=Official
TXXX=MusicBrainz Album Type=compilation
TXXX=MusicBrainz Artist Id=44b16e44-da77-4580-b851-0d765904573e
```
As per the [TIT2 id3 tag](https://en.wikipedia.org/wiki/ID3#ID3v2_frame_specification), Simple Music Player is now correctly showing the title/songname as "Piano Concerto no. 1 in F-sharp minor..." (yesterday it was not correctly showing the title/songname, but I do not understand why, or what has changed - this may well be an issue with [my rom](https://lineageos.org/
)).

I'll close this now (if I can reproduce it, I'll re-open this, or reference it from a new bug report).

Many thanks, Jaime.


(zipped) test file: [pno-cs.mp3.zip](https://github.com/SimpleMobileTools/Simple-Music-Player/files/4286508/pno-cs.mp3.zip)
