### ISSUE TITLE
MediaStore.Audio.Media.DATA Deprication

### ISSUE THREAD

**Issue by neptu39701** [SimpleMobileTools/Simple-Music-Player#247]
Hi Since MediaStore.Audio.Media.DATA is deprecated in android q how do you find song file path?

**Comment by tibbi** [comment]
not sure, I wasnt working on that yet. The whole app will be remade to work on MediaStore and completely ignore file paths. Then I can implement playlists the proper way too. The app really needs a big rewrite, I dont like the way it works and looks.
