### ISSUE TITLE
Show Filename as Title enhancement

### ISSUE THREAD

**Issue by rlv-dan** [SimpleMobileTools/Simple-Music-Player#250]
Even if there is no ID3 tag, there is a pretty high chance the filename is in the format "Artist - Title.mp3" or similar format. It would be neat if this could be detected and used.

**Comment by tibbi** [comment]
you can already select using the filename as the app title in the app settings

**Comment by rlv-dan** [comment]
I think you misunderstood me. If there is no id3 tag the display says something like:

> Michael Jackson - Thriller
> <unknown>

If you where to detect the " - " it could be split to instead say:

> Thriller
> Michael Jackson

A tiny enhancement but it would be pretty neat.

**Comment by tibbi** [comment]
I dont plan adding that for now, would be too unreliable
