### ISSUE TITLE
Songs not resuming where we left

### ISSUE THREAD

**Issue by balaidm** [SimpleMobileTools/Simple-Music-Player#253]
Let say playing 12th song on some playlist. When we close and open app, it started playing first song on ama eplaylist instead 12th or 13th song.

**Comment by ruria** [comment]
I usually listen to long podcasts (few hours) , it's frustrating search the point where I left it each time I use stop / resume feature

**Comment by tibbi** [comment]
this should be solved already after the rewrite from 5.4.+
