### ISSUE TITLE
music stopping after one title finished

### ISSUE THREAD

**Issue by hakaishi** [SimpleMobileTools/Simple-Music-Player#255]
I have a Sony Xperia 8 (Android 9/10).
And the music always stops after one title ended when the display is turned off.
I already tried to add the app to the list of apps allowed to ignore power saving, but it's no use.
As soon as I turn on the display the next title is played.
VLC, Apollo, Music-Player-GO and others don't have this problem.

If I can help you in any way with additional information, please tell me.

**Comment by tibbi** [comment]
shouldnt happen anymore
