### ISSUE TITLE
Add A-B Repeat function

### ISSUE THREAD

**Issue by xxxxq64** [SimpleMobileTools/Simple-Music-Player#256]
Hello,

can you add A-B Repeat function?

Does it fit to your concept as a simple music player?

**Comment by tibbi** [comment]
not really, it sounds like a quite unnecessary function that so far nobody requested. Repeating only one song is the most used one.

**Comment by xxxxq64** [comment]
Pity :(



Do you know an open source music player app on Android with A-B repeat function?  I am looking for such an app.

**Comment by tibbi** [comment]
Ive never heard about such, not even a closed source one :) I guess you can just create a playlist with those 2 songs and do it like that.

**Comment by xxxxq64** [comment]
What do you mean?

I would like to have for 1 song only the here repeating user defined part between A and B point.

I only know VLC video player has this A-B repeat function.

But it is a media player and it is more specialized for video files and I don't like the UI.

**Comment by tibbi** [comment]
aha, I thought you mean repeating 2 songs. You cannot set repetition between 2 points in 1 song in this music player.

**Comment by xxxxq64** [comment]
:D
Now you know exactly what I mean.

Can you add such a function and will the report open again?

**Comment by tibbi** [comment]
no, it isnt on the roadmap so still dont expect having it :) Nobody needed it so far.

**Comment by xxxxq64** [comment]
It is only a feature request.

**Comment by tibbi** [comment]
it still doesnt fit into the roadmap, it is a way too advanced feature
