### ISSUE TITLE
Search function unreliable

### ISSUE THREAD

**Issue by adrian5** [SimpleMobileTools/Simple-Music-Player#279]
When searching for tracks I want to play back, I have limited success. This is since the recent overhaul of the App.

One example of a file that doesn't get found (but is listed and playable via a folder/playlist) is the following:

```text
File: Smashing Pumpkins - 1979.flac

[Meta]

Artists: Smashing Pumpkins
Title: 1979
```

Could this be related to it being FLAC?

---

Anyway, in the old App I was definitely able to search that very group. I also think it would be nice if search was more fuzzy/forgiving.

Version: 5.4.2

**Comment by tibbi** [comment]
what are you searching by? Currently only the visible fields are searched, menaing the app title at the Tracks tab

**Comment by adrian5** [comment]
Do you mean that currently, searching for tracks (in playlists) is not supported? My "Tracks" tab is indeed empty.

**Comment by tibbi** [comment]
it is supported, but it searches only by title. So in your case that would be "1979". If you search "Pumpkins" or so, it wont find anything indeed

**Comment by adrian5** [comment]
I see, that would explain it.

I played around some more with the App and ran into other bugs such a playlists disappearing and reappearing. I then tried to recreate the playlists anew, in case them being from the older version was causing issues. As it turns out, any playlists I create from folders are empty (0 tracks), so I cannot even test search right now.
