### ISSUE TITLE
Doesn't load music on MicroSD card

### ISSUE THREAD

**Issue by adamzea** [SimpleMobileTools/Simple-Music-Player#280]
All of my music is on a MicroSD card. Simple-Music-Player doesn't seem to have any method of adding the music folder to the library. Therefore I'm stuck with zero tracks. Perhaps the settings need a "manage folders" preference section?

**Comment by tibbi** [comment]
What app version are you using? Make sure it is the latest 5.4.3, there you can create playlists and adding files or whole folders in them.

**Comment by adamzea** [comment]
5.4.2 is the newest version available in F-Droid, so that's the one I have. Adding a folder to a playlist says "No items found".  Does it not read subfolders?  If I dig down to an Artist >Album folder that contains MP3s, then it will create a playlist but then lists it as "No items found" even though MP3s are within there. All of the MP3s work in other music players such as JetAudio, YT Music, etc.

**Comment by tibbi** [comment]
it doesnt work recursively currently

**Comment by adamzea** [comment]
TODAY... it shows 10,000 songs!  I guess it just took a really long time to browse the folders?  In that case, I think you need a "scanning 1 of 10,000..." progress indicator/message so that we know the app is actually doing something.  Launching it and having no music tracks appear (even when manually trying to add them) makes it feel broken.

**Comment by tibbi** [comment]
Ill see how could it be improved. That isnt really a casual scenario to have that many songs. So far not a single person had such an issue.

**Comment by tibbi** [comment]
I guess scanning works then, it is some different issue to not see a progressbar.
