### ISSUE TITLE
Blank Notification

### ISSUE THREAD

**Issue by manish2525** [SimpleMobileTools/Simple-Music-Player#281]
Getting Blank notification (with not working audio controls) when I push audio and kill the app then restart it.

Device model name - SM.-J701F/DS
Android version - 8.1.0
App version - 5.4.3

![Screenshot_1](https://user-images.githubusercontent.com/35685264/98204556-45986680-1f5c-11eb-8fcc-604677b6cf89.png)

**Comment by tibbi** [comment]
shouldnt be happening anymore
