### ISSUE TITLE
A "Play All" button would make the UI much easier

### ISSUE THREAD

**Issue by adamzea** [SimpleMobileTools/Simple-Music-Player#283]
It appears that I have to dig down into the music library to find a track before the Simple Music Player will start playing music.  That's way too complicated as a user interface.  A big "Play All" button on the launch screen would make the interface much more simple and easy to use.  It should be close to the bottom/center of the screen because that's where a person's thumb is going to be when holding the phone. It's foolish to put buttons at the top because that requires users to poke at them with a second hand. It's much more efficient to design the UI for single-hand thumb usage.
Anyway, here's a mockup of what the home screen could look like. One touch "play all" button would make getting to the actual music player much more simple.
![Screenshot_2020-11-05-11-32-04-621](https://user-images.githubusercontent.com/24486391/98270592-061e4a00-1f5d-11eb-89d0-fc7e621f128a.jpg)

This interface could make playing other music within the library much easier too. For example, when selecting an artist or album, the button could show as "Play Selected".

![Screenshot_2020-11-05-11-32-04-621_playselected](https://user-images.githubusercontent.com/24486391/98270788-3665e880-1f5d-11eb-8807-cdbc39e6e537.jpg)

**Comment by tibbi** [comment]
well just swipe to Tracks and click on a track. That will play all.

**Comment by adamzea** [comment]
> well just swipe to Tracks and click on a track. That will play all.

Three swipes and a tap??  That's not simple at all!  It's also not nearly as easily discoverable as an actual play button.

**Comment by tibbi** [comment]
if you dont want to use artists, albums etc, just ignore them and stay on the Tracks tab. You will be just 1 click away from playing all, guess you can handle it.

**Comment by adamzea** [comment]
> if you dont want to use artists, albums etc, just ignore them and stay on the Tracks tab. You will be just 1 click away from playing all, guess you can handle it.

That doesn't solve the discoverability problem.  Also, it doesn't work. If I leave the app on the "Tracks" tab, close, relaunch, then the "Tracks" tab does appear by default, but it is completely blank, thus making it impossible to start playing music without going back to the "Playlists" tab and opening "All Tracks".  So with that method I need to do 3 swipes and two taps in order to get the music to play = 500% more work. That's a significant reduction in usability. 
See below for how the "Tracks" tab appears after relaunching the app.  Shall I file that as a new bug? 

![Screenshot_2020-11-05-14-51-46-409](https://user-images.githubusercontent.com/24486391/98289987-fca1db80-1f76-11eb-8650-3e7d8370cbeb.jpg)

**Comment by tibbi** [comment]
ye, but first make sure that it isnt just slow, you have a lot of files there. Also try reinstalling the app just to ensure that everything gets fetched properly

**Comment by adamzea** [comment]
> ye, but first make sure that it isnt just slow, you have a lot of files there. Also try reinstalling the app just to ensure that everything gets fetched properly

Does it RE-Fetch after every restart??  Everything is in Playlists > "All tracks" and they're playing fine, but Artists, Albums, Tracks tabs are empty now. 10,000 songs is not that many.  An iPod from 2003 (17 years ago) could handle that many songs. 

Anyway, just trying to help as a lot of FOSS programs could gain a lot more users if they put more focus on usability design.

**Comment by tibbi** [comment]
that is a whole new system of fetching media now, it has been rewritten just a couple days ago. Many things are still waiting for improvements.

**Comment by adamzea** [comment]
Oh ok.  Yeah, getting the media scanning working well is certainly more important.
