### ISSUE TITLE
Disable playlist repetition

### ISSUE THREAD

**Issue by Welteam** [SimpleMobileTools/Simple-Music-Player#286]
In most music apps, the loopback mode has 3 states:
1. Disabled
2. Playlist repetition
3. Song repetition

Here the loopback button only switch between state 2 and 3. I don't see any way to stop the music at the end of the playlist.

**Comment by FWDekker** [comment]
Disabling repetition would be nice because sometimes I just want to listen to an album, and stop listening after that. Currently, I often don't notice that an album has restarted playing and I end up listening to an album multiple times by accident.

**Comment by qwertyfinger** [comment]
@tibbi What do you think of tackling this one along with #332? It would be easier to implement them sequentially. Also, I think this is an even more frequently used feature than "stop playback after 1 song".

**Comment by tibbi** [comment]
sure, can be added

**Comment by tibbi** [comment]
will be added in 5.7.1
