### ISSUE TITLE
new permission needed? read phone status and identity.

### ISSUE THREAD

**Issue by itmike** [SimpleMobileTools/Simple-Music-Player#29]
I didn't see this mentioned in the change log. But, fdroid notified me that this is now needed. Why?

**Comment by tibbi** [comment]
yes, it has been added quite a while ago. Phone status is needed for detecting incoming calls, so I can pause the music. Im not using any identity type of thing, they just happen to be in 1 group.

**Comment by itmike** [comment]
Ok. Good to know and to bad it can't be choosen more fine grained. Thanks for your prompt reply!
