### ISSUE TITLE
Current track, controls and playlist on same screen at same time

### ISSUE THREAD

**Issue by uoee** [SimpleMobileTools/Simple-Music-Player#291]
Hi. There was a recent-ish change in the user interface. I think this was the change to version 5.4.

One thing I liked about the old interface was that I could see more information at the same time (current track info at top, audio controls below, playlist below that, no cover art).

I couldn't see a way in the new UI to always show multiple components this way, so I reverted back to version 5.3.4. Perhaps some time you could restore the way of using the app with more visible components.

Thanks very much for providing these apps; they've been a great help to me.

**Comment by tibbi** [comment]
I dont really plan reverting to that UI, thanks though

**Comment by uoee** [comment]
Sorry for any misunderstanding, but I didn't actually mean to suggest that the new UI is completely reverted (as in binned). Only that it would be nice to have an option of viewing more information on one screen (as part of any new UI framework).

**Comment by uoee** [comment]
Just to provide more feedback (this time with reasoning) while I'm here...

I mainly preferred having the playlist and controls together because it's easier to try out multiple tracks without having to switch between screens. This switching can be a little annoying. I often need to play and skip through various audio tracks before determining which I want to hear.

A second issue is that the space where the playlist was before is now taken up with a giant area intended for cover art. This area is often just an empty space or, worse, filled with some irritating random cover art. Either way, having the playlist still accessible would be more useful.

Anyway, I'll leave it there – no problem at all if you decide to ignore this suggestion. I'll live, and I'll continue to use the app. Thanks again.
