### ISSUE TITLE
View and Edit Audio Tagger

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Music-Player#298]
View and Edit Audio Tagger
![102224627-37027f00-3f0c-11eb-941d-1ef443c493bb](https://user-images.githubusercontent.com/75672019/102236968-21945180-3f1a-11eb-818d-020ef2d0a5b7.jpg)

**Comment by qwertyfinger** [comment]
On any Android version, the changes to metadata through MediaStore get reverted when the file is renamed or scanned by MediaScannerConnection: https://stackoverflow.com/a/60152702/3566013. I tested it on Android 8 and it's true.

The hack described in the answer above to at least temporarily edit metadata works on my Android 10 emulator but does not work on my Android 11 phone. Perhaps it only works for Android 10.

Seems like the only reliable solution is to use some ID3 tag editor library and then rewrite the file completely: https://stackoverflow.com/a/60066961/3566013.
Or to store the edited data only inside our application, so the changes would be saved locally in our app. But that would need a lot of refactoring.

@tibbi Should we proceed with any of the possible solutions or not implement this feature at all?

**Comment by tibbi** [comment]
I dont want to have the changes in our app only. Cant you research mediastore more? There has to be some way of doing it :)

**Comment by qwertyfinger** [comment]
> 
> 
> I dont want to have the changes in our app only. Cant you research mediastore more? There has to be some way of doing it :)

There's very little info available on this stuff, and it seems like I've already looked at everything I was able to find. I tried a stock Music player on my Sony that allows changing metadata – it had the same problem of it being reverted. Poweramp only changes metadata locally inside its own application. I will test some other apps and try to find some more info on MediaStore.

**Comment by tibbi** [comment]
how would storing info in our app only work? Does it need a new database?

**Comment by qwertyfinger** [comment]
Not sure about the details, I would need to take a look at what kind of a database we already have inside the app

**Comment by tibbi** [comment]
well okay, if you wont be able to fix it in general, we could go with updating it in our app only
