### ISSUE TITLE
Hardware buttons issue

### ISSUE THREAD

**Issue by stelariusinfinitek** [SimpleMobileTools/Simple-Music-Player#3]
Hi! 

First, I love this player, it's very fast. The only problem I have is that the hardware buttons aren't being recognised by the app. If I hold the volume up button from my headset, nothing happens. It works with other music player. I use CM 12.1 on a Samsung S3 if it helps. I can give you some logs if you need.

**Comment by tibbi** [comment]
can you test version 1.11 when its available in a couple hours please? I havent found any way to test it myself :)

**Comment by stelariusinfinitek** [comment]
I'm on 1.12. Still not working :(

**Comment by stelariusinfinitek** [comment]
I tested last night the 1.15 version from Google Play. The hardware buttons are still not working for changing the music :(

**Comment by stelariusinfinitek** [comment]
Still not working in 1.16, really tested it. I don't want to be insistent. Is there something I can do to help fixing this? I saw that the code for hardware buttons (changing the music with the headphone buttons by holding them) is there but it really is not working (or maybe that's just for changing the volume). I know you don't have any idea why this is not working or what to do, I fully understand that and it's not a shame. These Simple apps are really great, especially this music player which I like so much but can't use it more because I use the headphone buttons heavily (when I'm walking, running, with my bike).  

So, if you need my help somehow, ask for it. I'd like to fix this by myself but I don't have any idea about coding. Take your time and see what you can do.  

Thanks from me and the community! :)

**Comment by tibbi** [comment]
heh I will be probably buying new headphones soon as my current ones broke, so I will buy ones with volume controls :)

**Comment by tibbi** [comment]
or try some opensource Music Players and see which one works. There is for example https://play.google.com/store/apps/details?id=com.jams.music.player.de.repat , or pick another one from the list at https://github.com/pcqpcq/open-source-android-apps/blob/master/categories/multi_media.md

**Comment by stelariusinfinitek** [comment]
Thank you! :) I'll be watching.

**Comment by stelariusinfinitek** [comment]
So, last night I was reading some code from my ROM (some Cyanogenmod changelogs) and saw some code for headphone buttons and the comments said something about the play/pause button. In that moment I realised this must be what you implemented, so I installed Simple Music Player and tested this thing.  
  
If I press the play/pause headset button once, you already know what it's gonna happen... but if I press that button two times quickly, next song plays :) This is what I wanted (not like this but it's okay). I have some crashes when I open the settings in CM13, sometimes (unrelated to this issue).
 
So, this things works :) Not the way I thought but it's working.  I'm gonna close this now and you can write some code for the next and previous headset buttons when you have time.

**Comment by tibbi** [comment]
ye those action are intended, 1 click is play/pause, 2 clicks next song, 3 clicks restart / previous. These are pretty standard. The problem with extra headphone buttons and volume controls is that I dont have any hardware to test it, cannot even use an emulator. Ill hopefully get my hands on something useful.

**Comment by schmatzler** [comment]
Maybe my headset/device is a little buggy. I can only trigger the play/pause action. When I press the headset button on my Droid 4 quickly, it just stops the music and starts playing again.

Could you implement skipping to the next/previous song when the VOL UP/VOL DOWN button is being pressed down for 1-2 seconds? This is standard on every other player out there, but on this one it just turns the volume up to the maximum.

**Comment by tibbi** [comment]
so I have headset with volume buttons already, but as Ive read too late, they work only on iphones.. If I finally get some normal ones that work, I will test the most popular music players and see how will they work. If its often possible to switch songs with volume buttons, I might add it, even tho I dont really like the idea of it.

**Comment by schmatzler** [comment]
It's the default to use the phones built-in volume buttons to switch between tracks when the screen is turned off.
If it's not too hard to implement, I would really like that feature. :)

**Comment by tibbi** [comment]
I actually remember some cases when i accidentally switched songs with volume buttons. I hated that behaviour, so it will definitely be something disablable in the settings.

**Comment by tibbi** [comment]
should be improved already, create some new report if theres still some issues

**Comment by NextGenOP** [comment]
Hi,


I'm also having problems with the volume app and the down button for skipping tracks. I'm not sure why, but the main difference between this software and another that works is that this it use a seek button rather than a skip button.

Simple Music Player;
![Simple-Music-Player](https://github.com/SimpleMobileTools/Simple-Music-Player/assets/60586402/eef654bf-50a6-46af-a8d8-7b42e27fb094)
Spotify:
![Spotify](https://github.com/SimpleMobileTools/Simple-Music-Player/assets/60586402/e1d04144-4fd3-4b91-a304-64334c9eb581)
Pulse Music:
![Pulse Music](https://github.com/SimpleMobileTools/Simple-Music-Player/assets/60586402/e313c479-0ec0-4ef8-9d96-a664c69a68ab)
