### ISSUE TITLE
Fix Loading Everytime

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Music-Player#300]
(Notice Bug) when enter app 5 to 6 sec blank screen to load...Most of music player loading the music at first only after install the app. Not every every time to load the music so pls fix it.

![102224646-3c5fc980-3f0c-11eb-8356-f2df9f573b1a](https://user-images.githubusercontent.com/75672019/102237281-8485e880-3f1a-11eb-805a-ded2d7c8c075.jpg)

**Comment by kaikun97** [comment]
This seems to happen for large music collections (I counted about 1200 songs for mine) so it takes around 10 seconds, I think a good idea would be to either cache the albums assuming that MediaStore isn't being used. While over 1000 songs may be less common, the majority of music players for Android seem to handle it fine.

**Comment by tibbi** [comment]
caching has been added already
