### ISSUE TITLE
Colour Value

### ISSUE THREAD

**Issue by Github-com-foss** [SimpleMobileTools/Simple-Music-Player#303]
Pls add custom color value option in customize theme.

![102224631-3833ac00-3f0c-11eb-8524-9ff01489d1b4](https://user-images.githubusercontent.com/75672019/102238342-a3d14580-3f1b-11eb-86dd-db1388b41b44.jpg)

**Comment by tibbi** [comment]
some colors cannot be updated properly dynamically, so some presets had to be used.
