### ISSUE TITLE
Playlist doesn't play

### ISSUE THREAD

**Issue by dies00irae** [SimpleMobileTools/Simple-Music-Player#309]
My playlists are not working.  It looks like it is playing, but there is no sound and the progress bar stays at 0.  They worked fine when I first created them.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by dies00irae** [comment]
I'm using version 5.5.1

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by tibbi** [comment]
So is the issue related to any playlist, or all songs? Basically no song plays well?

**Comment by dies00irae** [comment]
It is just the playlists. None of the playlsts work. I can play songs from the tracks, albums, and artists.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by tibbi** [comment]
should be working already
