### ISSUE TITLE
Song change without pauses

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Music-Player#326]
[Feature] Songs need to stop playback a little moment to play the next song, some players like Spotify or Foobar have a function to instantly play the next song, without pauses (this is excellent for albums where the songs are like connected with smooth transitions)

**Comment by Kodmod** [comment]
Yes, please add seamless playback.

**Comment by tomas4** [comment]
+1

**Comment by Naveen3Singh** [comment]
Can you guys share a gapless album for testing? Of course, I can split an audio file into parts but an album would be nice too.

**Comment by Kodmod** [comment]
@Naveen3Singh The Dark Side of the Moon is a good one. Especially the transition between `Speak to me` and `Breathe`.

**Comment by Naveen3Singh** [comment]
It seems to be working fine for me so here's an initial test APK with support for gapless playback: https://github.com/Naveen3Singh/Simple-Music-Player/releases/download/gapless_playback_test/music-player-core-debug.apk

Please let me know if it's working as expected or if you across any other issues. Thanks!

**Comment by tibbi** [comment]
gapless playback has been added already

**Comment by ralhei** [comment]
Wow, this is great. However, in the currently latest version 5.16.5 available in the fdroid store, the gapless playback is either not yet included, or isn't real gapless, I can still hear the split between one song and the next ...

**Comment by Naveen3Singh** [comment]
> Wow, this is great. However, in the currently latest version 5.16.5 available in the fdroid store, the gapless playback feature is either not yet included, or isn't really gapless, I can still hear the split between one song and the next ...

You have to enable gapless playback in settings.

**Comment by ralhei** [comment]
Cooool - this was the missing piece. Thank you so much. It's such a great player. :-)

**Comment by tomas4** [comment]
First try and it seems to work. Awesome for some later Beatles albums, thanks.
