### ISSUE TITLE
(feature request) Allow Specific Files To Be Ignored

### ISSUE THREAD

**Issue by puppykickr** [SimpleMobileTools/Simple-Music-Player#327]
I have a number of files that I would like for this app to ignore.

Could an ignore list be implemented, perhaps by long pressing the folder and/or the file itself?

**Comment by tibbi** [comment]
ignoring on which tab you mean? Playlists, albums, or?

**Comment by puppykickr** [comment]
No, files.
Such as sound files.

I have a few sound effects that Simple Music Player thinks are songs.
One of which is the sound of a LRAD device, which I use for a ringtone in very loud areas.

Obviously, this is undesireable when listening to music in the car-  when between songs a LRAD comes on at full tilt.

The file is stored in a separate folder from my music in my file manager.

If there was implementation of an included/excluded files item in the settings of Simple Music Player, much the same as you have in Simple Gallery, then I could simply (no pun intended) exclude the folder that has undesireable sounds in it.

**Comment by kenchou** [comment]
I encountered a similar situation: The player list all my call recording. It's terrible.

I think the better way is to specify the scan directories like most other players.

**Comment by TheMaestro1s** [comment]
Any update?
Recordings files such as WhatsApp files really annoying me :'(

**Comment by puppykickr** [comment]
@kenchou The idea of excluding folders would be easier, as (A) this already exists in other apps from the same developer and (B) it eliminates the need to place all music into the only folders that are seen by the app.

**Comment by betsythefc** [comment]
This app shows all my audiobooks, voice recordings, and other random ones mixed in with my music. An include or exclude, same as Simple Gallery, would be great!

**Comment by tibbi** [comment]
there is already a Folders tab, you can exclude them and the files will be excluded from everywhere
