### ISSUE TITLE
Change Color Dialog

### ISSUE THREAD

**Issue by nlover6** [SimpleMobileTools/Simple-Music-Player#33]
In Setting -> Customize Colors -> When click any item to change a color, dialog show in white theme and (Ok, Cancel) buttons is white too, and cant see buttons.
My phone's android is 7.1.1

**Comment by tibbi** [comment]
Hello indeed, its a bug with Android 7, Ill try to release a fixed version today.

**Comment by tibbi** [comment]
should be fixed with 2.0.1
