### ISSUE TITLE
Play command via Headphone no longer working

### ISSUE THREAD

**Issue by Aufschlauer** [SimpleMobileTools/Simple-Music-Player#330]
Hi,

I've the combination Sony WH-1000XM2 Headphone + Android 7.1.2 + Simple-Music-Player v5.6.5.

Since a few version the play command from headphone is no longer working. Whereas the stop, next- and prev song command continues to work.

Anyone else with this problem?

Thx!

**Comment by tibbi** [comment]
try upgrading to 5.7.0
