### ISSUE TITLE
Add option to pause song when finished

### ISSUE THREAD

**Issue by Glitchy-Tozier** [SimpleMobileTools/Simple-Music-Player#332]
**Is your feature request related to a problem? Please describe.**
Sometimes people don't want to binge through their music, but instead only listen to one track and then have the playing stop until they want to listen to the next track. It can be annoying to immediately be bombarded with a different song.

I haven't found any option that could result in the desired pausing-behaviour.

**Describe the solution you'd like**
In the spot where the user can select whether the song should loop or not, add a fourth option: pause.
This option should pause and the current song when it's done playing.

**Additional context**
Unfortunately, most open-source music players lack this feature.
![Screenshot_20210706-150835_Music Player.jpg](https://user-images.githubusercontent.com/59611881/124605360-1bd96b80-de6c-11eb-844e-5c643130beb2.jpg)

**Comment by qwertyfinger** [comment]
@tibbi Not sure if using ["Repeat" icon](https://fonts.google.com/icons?icon.query=repeat) for putting the song on repeat and ["Repeat One" icon](https://fonts.google.com/icons?icon.query=repeat+one) for stopping the playback after one song will be a friendly UX. I think it might be confusing for a lot of people.

Maybe some "1" icon would be more appropriate like here, for example?
https://www.shoutbabble.com/musicolet-stops-after-each-song-on-android-device/

**Comment by qwertyfinger** [comment]
Perhaps something like this.
![image](https://user-images.githubusercontent.com/7561414/129927530-51d51a12-eeac-4b5d-a851-f1edd7baa975.png)

**Comment by Glitchy-Tozier** [comment]
>Maybe some "1" icon would be more appropriate like here, for example?

I absolutely agree, this or maybe even a pause-icon.

**Comment by tibbi** [comment]
yeah, you can use something like that. Maybe we could add both options, like repeat 1 song and stop after 1 song actually. Have toast messages in both cases, it will make it clearer.

**Comment by qwertyfinger** [comment]
Yes, of course, repeat 1 song option will remain. Why 4 states? I can see 3:
1. default
2. repeat 1 song
3. stop after 1 song.

**Comment by qwertyfinger** [comment]
Also, what should the toast messages be – "Stop playback after one song" and "Continue playback after one song"?

**Comment by tibbi** [comment]
Right, 3 states only. I thought I have a repeat queue there too, nevermind then. Make it "Stop playback after current song"

**Comment by tibbi** [comment]
will be added in 5.7.1
