### ISSUE TITLE
Specify library folder

### ISSUE THREAD

**Issue by olibac** [SimpleMobileTools/Simple-Music-Player#334]
Hello,

I own Simple Gallery and File Manager. I am just starting with Music Player (free).
I would like be able to specify a folder where all my music is located. I would prefer not to have WhatsApp/Skype/AnyOtherApp audios shown in my music app.

Best regards

**Comment by tibbi** [comment]
Well the Music Player doesnt store any files anywhere, it just shows existing ones.

**Comment by olibac** [comment]
Excuse me, surely I have not explained myself well. I know that the player does not store files, it only displays them.
That's why I was saying that it would be nice to be able to specify a folder and the player to only show/analyze the files that are in that folder. Thus preventing audio files that are not music from appearing, for example, WhatsApp/Skype audios or any other application that can receive/send audio files. In my case, I have all the music in the "mymusic" folder, that's the only folder I would like to be scanned by the player.

**Comment by tibbi** [comment]
Right, I see. The app soon wont be able to access the Storage permission, so I dont want to work on such features anymore.

**Comment by olibac** [comment]
Anyway, thanks for the effort of creating these apps :)

**Comment by sebastianschauenburg** [comment]
Wanted to raise this point as well, but apparently it's a choice (which is fine btw).

@olibac in case you are still looking, have a look at [mucke](https://github.com/moritz-weber/mucke).
