### ISSUE TITLE
Use "track" instead of "song"

### ISSUE THREAD

**Issue by qwertyfinger** [SimpleMobileTools/Simple-Music-Player#338]
I think it might make sense to use the word "track" instead of "song" since not every audio file that might be played is a song.

**Comment by tibbi** [comment]
where?

**Comment by qwertyfinger** [comment]
In text descriptions – "Delete current songs", "All songs", "Repeat current song" etc.

**Comment by qwertyfinger** [comment]
It's obviously just a suggestion and won't affect user experience much anyway

**Comment by tibbi** [comment]
you mean in strings.xml only? That is not relevant, some of them are not used anymore
