### ISSUE TITLE
current offset and precise seek to offset

### ISSUE THREAD

**Issue by jpritikin** [SimpleMobileTools/Simple-Music-Player#34]
Sometimes I listen to really long recordings, like a single MP3 of 10 hours. It would be great if you could show the current time offset during playback and offer a way that I could seek to a specific offset by typing the time code or similar. I'm not sure about the best user interface, but the current ability to seek by tapping on the playback line is not precise enough for long recordings. I can tap with about 10-20 min precision, but I'd really like to seek to, say, 3:47:23 (that is 3 hours, 47 minutes and 23 seconds).

**Comment by tibbi** [comment]
even if it isnt a precise seek, a helper will be added in version 3.2.0. If you tap the current or max duration you can skip forward/backward by 2%. The seekbar itself will be a bit shorter than previously.

**Comment by jpritikin** [comment]
On Thu, Feb 08, 2018 at 11:18:44AM +0000, Tibor Kaputa wrote:
>    even if it isnt a precise seek, a helper will be added in version
>    3.2.0. If you tap the current or max duration you can skip
>    forward/backward by 2%. The seekbar itself will be a bit shorter than
>    previously.

That would be an improvement.

Thank you.

**Comment by tibbi** [comment]
should be working already
