### ISSUE TITLE
Plural for the values 2, 3 and 4

### ISSUE THREAD

**Issue by Valdnet** [SimpleMobileTools/Simple-Music-Player#345]
In text strings there is no plural for the values 2, 3 and 4. In various languages, e.g. in Polish, the inflection for the plural differs from the number 5, 6, etc.

Example:

> 1 album
> 2 album**y**
> 3 album**y**
> 4 album**y**
> 5 albumów

https://github.com/SimpleMobileTools/Simple-Music-Player/blob/e4d1e15644993bfcb7e34adcf5a1e8ee4e5abd16/app/src/main/res/values-pl/strings.xml#L59-L63

https://github.com/SimpleMobileTools/Simple-Music-Player/blob/e4d1e15644993bfcb7e34adcf5a1e8ee4e5abd16/app/src/main/res/values-pl/strings.xml#L65-L69

For the above text strings, add:

```
<item quantity="one"></item>
<item quantity="few"></item>
<item quantity="many"></item>
<item quantity="other"></item>
```
so that translators see that these variations need to be translated.

**Comment by tibbi** [comment]
translations are handled by volunteers, if you want to help the guide is at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file . Thanks
