### ISSUE TITLE
Sleep timer deactivation

### ISSUE THREAD

**Issue by Valdnet** [SimpleMobileTools/Simple-Music-Player#347]
Steps:

1. Play the song.
2. Set the sleep timer for e.g. 5 minutes.
3. Attempt to deactivate the sleep timer.

The sleep timer cannot be deactivated.

If I set the sleep timer for e.g. 5 minutes. Then if I want to opt out of automatically disabling the app, there is no way of deactivating the sleep timer.

Apps:
Android 10
Simple Music Player 5.7.1

**Comment by tibbi** [comment]
why cannot you deactivate it? Pressing it doesnt work, or just nothing happens if you click the "X" for canceling it?

**Comment by Valdnet** [comment]
> Pressing it doesnt work, or just nothing happens if you click the "X" for canceling it?

And I also guessed it and tested it to be sure, but for the user, the sleep timer function is still active, because it is indicated by the selection of the option in the sleep timer.

There should be an option to check, for example, "Disable" or an option to uncheck the selected sleep timer option.

**Comment by tibbi** [comment]
So there is no visual indication of the running sleep timer, but it is still active and shuts down the app after some time?

**Comment by Valdnet** [comment]
There should be information about the status of the sleep timer or the option to select the off sleep timer in its settings window.

An example of a sleep timer setting window:

- [ ] 5 minutes
- [ ] 10 minutes
- [ ] 30 minutes
- [ ] 1 hour
- [ ] Disabled

**Comment by tibbi** [comment]
dont you see the remaining time at the bottom right corner?

**Comment by Valdnet** [comment]
Ahhh. Well. Somehow the countdown window merged with the app's main window, and I didn't notice it. I think it is well resolved. Thanks for the information 😉.

I close the issue.
