### ISSUE TITLE
Show title of current track near progress bar

### ISSUE THREAD

**Issue by lianergoist** [SimpleMobileTools/Simple-Music-Player#348]
The layout of the player show a list (Playlist, Artist, Album, Track) and the name of the track currently playing and a play/pause button at the bottom. If you press (click) the name of the track, you get a 'layout' with progress bar, prev, next, etc. At the bottom, you now have the title of the next track. In this layout (the upper part, near the progress bar) I would suggest to also have the title of the current track. Please! And maybe also the title of previous and next track somewhere near the prev and next buttons. But most important: title of current track! Thanks!

**Comment by tibbi** [comment]
I dont plan adding that, it would make the UI too crowded. Thanks
