### ISSUE TITLE
Allow to specify the number of times a song is to be repeated

### ISSUE THREAD

**Issue by gitraghuram** [SimpleMobileTools/Simple-Music-Player#359]
This feature is very helpful when we try to play some songs for a number of times in order to memorize it, play some songs/tunes repeatedly in a party and so on.

Currently the repeat song icon would cycle from Repeat off, Repeat all, Repeat current song, and Stop playback after current song.
i)  It would be helpful to be able to repeat for a specific number of times. 
ii) This could be for (a) the whole album, or (b) for current song, or (c) for each song.
Let us say an album contains songs x,y, and z.
If the user says to repeat 4 times, then the playing sequence in the three options above would be:
a) x,y,z, x,y,z, x,y,z, x,y,z
b) (assuming y is current song),  x,y,y,y,y,z
c) x,x,x,x, y,y,y,y, z,z,z,z

iii) There could also be an advanced feature, where repetition number could be specified for each song separately, or, a default repetition count and a specific repetition count for some of the songs individually.

iv) As the songs play, it would be good to show a number representing the number of times remaining to be repeated.

v) The repetition number could be as big as the system allows.

vi) This could work with Shuffle ON as well, with the repetitions of a song completing before going to the next song.

This feature is very helpful when we try to play some songs for a number of times in order to memorize it, play some songs/tunes repeatedly in a party and so on.

**Comment by tibbi** [comment]
such repetition setter is way too advanced, I dont think it should be in this app

**Comment by gitraghuram** [comment]
While the full set of requested features may be advanced, please see if the following is a good step:

A) Wherever a repeat is allowed, allow for a number to be input which represents the repeat count. Then instead of repeating forever, repeat for that many times and move on.

**Comment by tibbi** [comment]
that is not on the roadmap either

**Comment by gitraghuram** [comment]
Not sure whether feature requests should be present in the roadmap first.
I am new to this workflow, kindly help.
