### ISSUE TITLE
Can't Get Filename To Show Instead of Song Title

### ISSUE THREAD

**Issue by GithubContributor832** [SimpleMobileTools/Simple-Music-Player#370]
I can't get filename to show instead of song title when option "Show filename as song title" is set to always. Something I noticed recently and I'm running version 5.9.0.

**Comment by tibbi** [comment]
And what shows up at those files?

**Comment by GithubContributor832** [comment]
Song title is "Break Bread" and filename is "04 Break Bread". Option "Show filename as song title" is set to always and only shows title. If can confirm via properties.
