### ISSUE TITLE
Disconnecting earphones crashes the player

### ISSUE THREAD

**Issue by edo0** [SimpleMobileTools/Simple-Music-Player#376]
Dear Tibor, 
Thank you for your work on Simple Mobile Tools
I have found out this bug on LineageOS 18.1 / Android 11

Steps to reproduce:
- Play music with headphones
- Leave Simple Music Player (or also staying into it, I found)
- Disconnect headphones
- The outcome is that instead of pausing the song, the player crashes: the player indicator disappears from the notifications area, and when you return to the app, the player leaves the place to the background page, leaving no way to resume the song from where you left

Please find the behaviour shown in this recording (since I use no headset indicator, refer to second 14 for removal of my headphones). This can be reproduced at all times and with different headsets.

https://www.brogiolo.eu/nextcloud/s/bCaZje35w3q9G5b

**Comment by tibbi** [comment]
what app version are you using?

**Comment by edo0** [comment]
I have just tried downgrading to both 5.8.2 and 5.8.1 from F-droid, and they exhibit the same bug
