### ISSUE TITLE
file ist not listed in foldres-view

### ISSUE THREAD

**Issue by losgehts** [SimpleMobileTools/Simple-Music-Player#389]
[mp3-file.zip](https://github.com/SimpleMobileTools/Simple-Music-Player/files/8318003/mp3-file.zip)

If I create a folder "Testmp3" and copy the atached mp3-file in that folder than Simple-Music-Player shows the folder in the "folders-list" and tells, that there is 1 Track. That is what I expect:
![list-of-folders](https://user-images.githubusercontent.com/36561586/159331555-bd51c035-f8e2-4e0e-88c0-22288cd49194.png)

Then I click on this folder it says "no items found". I expect, that it shows me this mp3-file:
![folder-content](https://user-images.githubusercontent.com/36561586/159332298-ab272c7a-144f-46fb-9902-724d3ab23049.png)

I am using Simple-Mobile-Player 5.9.1 on Android 10 on an Xiaomi Mi A2 Lite. 

On an other Phone (Samsung) Simple-Music-Player shows the same behavior.

**Comment by tibbi** [comment]
you use a pretty old app version, upgrade to 5.10.1 please. Some things have been improved already.
