### ISSUE TITLE
Activity Thread issue app crashes due to notification/service

### ISSUE THREAD

**Issue by AnsShahG** [SimpleMobileTools/Simple-Music-Player#390]
Fatal Exception: android.app.RemoteServiceException
Context.startForegroundService() did not then call Service.startForeground()

**Comment by tibbi** [comment]
what app and OS version are you using? When does it happen?

**Comment by AnsShahG** [comment]
android 8 to android 10 it happens without any reason

**Comment by tibbi** [comment]
retry with 5.11.0 once it becomes available please
