### ISSUE TITLE
v5.11.2: No music files are found

### ISSUE THREAD

**Issue by StefanPofahl** [SimpleMobileTools/Simple-Music-Player#394]
Thanks for the new version!
currently I face the following issue:
mp3-files are stored in "/storage/emulated/0/Music", but in the application there is neither an Album nor an Artist listed.
I am sure there is an explanation and a way to cure the issue, it would be nice to add this issue in the list of FAQ.

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by StefanPofahl** [comment]
Simple-Music-Player, Android v9

**Comment by tibbi** [comment]
are they some casual mp3 files, or what ones?

**Comment by StefanPofahl** [comment]
I start from the beginning, out of a sudden my music was gone. I investigated my folder structure and I was not able to find the mp3-files. Next step was I copied new mp3-files onto my mobile. Nothing happened inside the "simple music player", the albums and titles where still missing. Here some screen shots:

![overall_folder_structure](https://user-images.githubusercontent.com/65159315/164611231-46a163cb-fc7a-4b05-a1e8-a6d57f9bd1e5.png)

![Music_folder](https://user-images.githubusercontent.com/65159315/164611220-2ff7a96e-9365-4f89-ace3-7ae3e490417b.png)

![example_folder](https://user-images.githubusercontent.com/65159315/164611205-a586641f-9c98-469e-8f84-e1dffbe73e10.png)

.
Here a few screen shots form the (failed) attempt to set up a play list:
[add_songs_to_play_list.pdf](https://github.com/SimpleMobileTools/Simple-Music-Player/files/8537484/add_songs_to_play_list.pdf)

I hope it helps to understand the issue.

P.S.:
The music app "Pulse Music" has no problems to find my albums.

**Comment by Naveen3Singh** [comment]
@StefanPofahl Are you still experiencing this issue? Do the music files appear if you force-stop/restart the app?

**Comment by StefanPofahl** [comment]
The situation has improved. The new version of your SW is similar to the characteristic of the app "Pulse Music". 
After update you player finds at least two albums, the other music is still missing :-( 
It seems, if as these two folders are special / are different from the folders of the other albums.
Is it allowed, two have two levels of folders? 
top: Artist
sub: Album

**Comment by Naveen3Singh** [comment]
Hello! @StefanPofahl 

I have uploaded a test APK with potential fix for this issue, please check if you are interested:
https://github.com/Naveen3Singh/Simple-Music-Player/releases/download/improved_media_scan/music-player-prepaid-debug.apk

Let me know if it works, thanks.

**Comment by StefanPofahl** [comment]
Thanks for the info! 
Today, I lost my mobile. And the other one has currently a MS-Windows Mobil OS.

**Comment by tibbi** [comment]
should be fixed in 5.17.0
