### ISSUE TITLE
progress bar in notification

### ISSUE THREAD

**Issue by narakai** [SimpleMobileTools/Simple-Music-Player#395]
The progress bar keeps going even if you paused playing.
And can not close notification bar if app is force closed.

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by narakai** [comment]
App: Simple Music Player
OS: Android 11

**Comment by tibbi** [comment]
but which music player version? I mean the number at the bottom of the About page.

**Comment by caligulaminus** [comment]
Hi, same issue here: when closing the app, progress bar in notification area and lock screen widget will not close.
Program version: 5.13.0
Android: 9

**Comment by tibbi** [comment]
should be fixed in 5.14.2
