### ISSUE TITLE
Playback is very loud

### ISSUE THREAD

**Issue by gutjuri** [SimpleMobileTools/Simple-Music-Player#396]
Hello,

when playing an audio file via Simple-Music-Player, playback is very loud, even on my phone's lowest volume setting. For some files, even the lowest volume setting is unbearably loud, making the app unusable to me.

I'd appreciate it if there was a setting "maximum volume", which scales the available volume range in the app.

Best Regards!

**Comment by tibbi** [comment]
those things are handled by the system, not us at all. There are multiple audio streams, do other music players play it well?

**Comment by gutjuri** [comment]
No, when playing from the Spotify App or other Apps the volume is considerably lower.

Do you know if there's a way to make Simple-Music-Player quieter?
