### ISSUE TITLE
Add seek buttons

### ISSUE THREAD

**Issue by Friptick** [SimpleMobileTools/Simple-Music-Player#398]
Feature request. Please add **seek buttons**, i.e. **fast-forward** and **rewind** in x-second increments.

Thanks for considering.

**Comment by tibbi** [comment]
you can already click curren or max duration for that

**Comment by Friptick** [comment]
@tibbi On version 5.11.2 (latest F-Droid for my device), the **<<** and **>>** buttons only skip to the next episode. I see no setting to change this behavior.

Is seek a feature in a later version?

**Comment by tibbi** [comment]
you mean on the notification or where? Inside the app you can click the current and max duration, the time value itself

**Comment by Friptick** [comment]
Ah indeed! That works, thanks. Maybe some chevron arrows would be an idea. I tried tapping everywhere except there, apparently.

Thanks.

**Comment by tibbi** [comment]
it is described in the FAQ too
