### ISSUE TITLE
Headphone Symbol Without Headphones In Use

### ISSUE THREAD

**Issue by HonestAbe7** [SimpleMobileTools/Simple-Music-Player#400]
I noticed that the headphone symbol in the status bar is shown when playing a song; but I don't have any earbuds or headphones in use now on my cell phone.

**Comment by tibbi** [comment]
what symbol you mean? Isnt it handled by the system instead of an app?

**Comment by HonestAbe7** [comment]
There is a headphone symbol like when I plug my earbuds in when playing music on the status. I have no idea since I am not a programmer or developer.

**Comment by tibbi** [comment]
right, that is the system one then, it is unrelated to our app

**Comment by HonestAbe7** [comment]
If it is unrelated to your app, then why does it only happen with your music app?

**Comment by tibbi** [comment]
Im not sure, we arent adding the icon ourselves anymore. Maybe those other apps arent targeting the latest OS versions and something changed there recently.
