### ISSUE TITLE
Deletion should delete

### ISSUE THREAD

**Issue by Friptick** [SimpleMobileTools/Simple-Music-Player#401]
The delete button behavior is a bit difficult to understand.

In `Tracks` view, `delete` removes the track from the list but does not delete the file. Assuming this is intended, how would you get the track back in the list, given that the file still exists but is not visible? 

Is it possible for the app to simply use the filesystem as its data model, rather than (as seems to be the case) maintaining a separate database which must always be synchronized (which I cannot see how to do)?

Thanks for advice, and for your work.

v5.11.2

**Comment by tibbi** [comment]
Delete always deletes the file itself, only at playlists it just removes them from the playlist. Delete and Remove are already 2 separate buttons though.

**Comment by tibbi** [comment]
not sure, report it as a separate issue with steps for reproduction
