### ISSUE TITLE
Delete button does not delete file

### ISSUE THREAD

**Issue by Friptick** [SimpleMobileTools/Simple-Music-Player#402]
Further to #401.

Steps to reproduce:
1. in `Tracks` view, long-press `Track_1`
2. tap Trashcan icon (causing `Track_1` to disappear from the list as expected)
3. in Simple File Manager, go to `Track_1`'s folder. `Track_1` is still there! And tapping it will play it in Simple Music Player

v5.11.2
Android 8.1

**Update.** Looking into this a bit, it is probably an issue with Android's "media database", which is out of sync. You are probably going to say that this is out of the control of Simple Music Player. Fair enough. Any suggestion of a config change or a workaround would be appreciated.

**Comment by HonestAbe7** [comment]
My issue is that the delete button automatically deletes it from the device as well as in the music player by default. I noticed this and had to put the files back.

**Comment by Friptick** [comment]
@HonestAbe7 In fairness to the dev, the button you are talking about is a "Remove from playlist" button, with an icon to match. I believe a "Delete" button would have a trashcan icon.

**Comment by HonestAbe7** [comment]
I see your point but I would suggest a "hide" from list button instead and a promot saying the file will be permanently deleted outside the playlist. I mean, why would you want to delete music files inside the player but instead a file manager?

**Comment by HonestAbe7** [comment]
I see your point but others music players specify whether it will be deleted from the playlist or permanently much better. I would like to see a popup saying are you sure you want to delete this forever or not? At least it does ask if you want to delete it outside a playlist but it can easily be misunderstood as thinking it would just be not in the list of files. But if you wanted to delete files wouldn't you just use a file manager to delete the files itself instead?

**Comment by Friptick** [comment]
Just an update. To check whether this is just a slow media database sync issue and the files eventually do get deleted, I have experimented by not touching the file manager for two weeks and using only the SMP delete button for audio files.

The files are all still there. The delete button unfortunately just does not delete the files at all.

**Comment by Friptick** [comment]
Thanks @naveensingh, very appreciated.
