### ISSUE TITLE
Sorting needs sorting.

### ISSUE THREAD

**Issue by Rbagman** [SimpleMobileTools/Simple-Music-Player#41]
Unknowns should go to the back of the sorting line.

Sort by artist should list the artist name line 1 followed by track name.

Sort by file name should show the actual file name with dot file  extension.

Hope this app is the one. Past players are great indoors, but they get retarded as soon as I hit the street — non responsive from the lock screen when I tap for next track or lagging so bad I can't  keep track of how many tracks I skipped over.

**Comment by tibbi** [comment]
should be solved in 5.4
