### ISSUE TITLE
Switching tabs while searching hides non-matching tracks/albums

### ISSUE THREAD

**Issue by serkonda7** [SimpleMobileTools/Simple-Music-Player#416]
**Reproduction**
1. Go to `Albums` or `Tracks` and enter a search
2. Switch to the other tab

**Actual Behaviour**
- Only tracks or albums are shown that match the search term
- Search bar is cleared
- Non-matching entries are completely hidden until restart

**Expected Behaviour**
- Save the search bar state and allow clearing manually
- Show all tracks or albums again

**Other information**
- Searching in `Artists` seems to be fine
- `Playlists` wasn't tested

**Comment by tibbi** [comment]
what app version are you using?

**Comment by serkonda7** [comment]
5.11.3

**Comment by dmint789** [comment]
Pretty sure this was just fixed in the new version, because I opened the same issue recently and it's closed now. The bug is gone for me.
