### ISSUE TITLE
Simple request: Play Song Next

### ISSUE THREAD

**Issue by dmint789** [SimpleMobileTools/Simple-Music-Player#426]
It's currently possible to enqueue songs, but they always go to the very end of the playlist. If you're playing your entire library, that means you won't hear the song until the very end of the playlist. Please also add a button that queues the song to be played after the current song.

**Comment by MaxsimLionel** [comment]
Second this.

**Comment by Th3FatKat** [comment]
This. An "enqueue next" option, perhaps changing to match Spotify's "Add to queue" button's behavior.
