### ISSUE TITLE
App crashes when loading big track queue

### ISSUE THREAD

**Issue by serkonda7** [SimpleMobileTools/Simple-Music-Player#440]
I have around 3000 songs.
When selecting one to play and look want to look into the track queue. The app crashes and my whole phone becomes unresponsive for about 30 seconds before i can force close.

**Comment by tibbi** [comment]
you mean that it freezes when you click on a song on the particular playlist? Or which tab are you at?

**Comment by serkonda7** [comment]
I'm in the songs tab and tap on a song to start it playing.
Then on the bottom I tap in the next song to open the track queue.
From here on app screen turns black and phone is unresponsive.
The current song keeps playing however

**Comment by Naveen3Singh** [comment]
@tibbi the QueueActivity freezes because the recycler view is wrapped by a nested scroll view and it tries to load everything all at once. It's similar to that issue in some other app I fixed some time ago.

**Comment by tibbi** [comment]
@Naveen3Singh so try fixing this too please
