### ISSUE TITLE
(Bug/Feature) Background audio playing not stoping 

### ISSUE THREAD

**Issue by PyICoder** [SimpleMobileTools/Simple-Music-Player#441]
The current background playing works, but even with the app closed it still has the notification and the music playing, I suggest a option or way to fix/address this by making the music and notification close when the app is close so it's not that intrusive.

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by PyICoder** [comment]
I am using the Simple Music Player app from F-Droid/Droid-ify(the modern ui), Android 7.0.

**Comment by tibbi** [comment]
but which app version? I mean the number at the bottom of the About section.

**Comment by PyICoder** [comment]
My apologies, the app version is 5.13.1.

**Comment by tibbi** [comment]
there is already an X on the notification, that stops playback. That is the expected behaviour, closing the app shouldnt stop the music.
