### ISSUE TITLE
[Bug] Playlists are sorted by title instead of track number

### ISSUE THREAD

**Issue by nameless326** [SimpleMobileTools/Simple-Music-Player#443]
someone reported the same issue a long time ago ([#160](https://github.com/SimpleMobileTools/Simple-Music-Player/issues/160)), but this bug is still present as of today.

(and yes, I'm using [5.13.1](https://github.com/SimpleMobileTools/Simple-Music-Player/releases/tag/5.13.1), the latest release of this app)

**Comment by ssihala** [comment]
@tibbi I have opened a PR that I believe fixes this issue

**Comment by nameless326** [comment]
it would be great if it got merged :(

**Comment by nameless326** [comment]
@tibbi can you please take a look at their PR?

**Comment by tibbi** [comment]
will do it, I wasnt working on this app lately

**Comment by tibbi** [comment]
sorting by track number will be added in 5.14.2

**Comment by nameless326** [comment]
oh, thank you!
