### ISSUE TITLE
Adding music

### ISSUE THREAD

**Issue by sum01** [SimpleMobileTools/Simple-Music-Player#45]
Addin music is very slow, as you can't just, say, add the whole music folder. My folder structure of {Music/artistname/albumname/songs} requires I select each album individually, which takes a long time on a new phone.

The app should probably have some sort of quicker way to do this. Some apps I've used had a scan option, but even just being able to add a folder higher up the structure would be enough.

**Comment by sum01** [comment]
At the moment, I got around this issue by uninstalling and reinstalling, which doesn't feel like a real solution, but a bandaid. If I ever add lots of albums then I'll have the same issue again.

**Comment by tibbi** [comment]
Ill maybe add a checkbox for adding folders recursively someday

**Comment by tibbi** [comment]
Ive made it always recursive, without any checkbox
