### ISSUE TITLE
I recommend not to translate

### ISSUE THREAD

**Issue by gallegonovato** [SimpleMobileTools/Simple-Music-Player#464]
Good afternoon @tibbi

I am contacting you, as I have seen on Weblate to translate Material You. But this is the new way to adapt Android icons, themes and so on. In Android 12 and 13.

You can find it at https://hosted.weblate.org/translate/simple-mobile-tools/simple-commons/es/?q=check:same

The only thing you could put Material You (Material Design 3). Since it is version 3 of Material Design.

The only thing if you want to put the translation, I do not know if Google gives another name. But in Spanish it would be: Material para ti

That's why I recommend marking this string in all languages so you can't change it. 

I apologize if this is not the way to communicate it. But by email it came back to me. And I put a comment in the string.

A hug and thank you for your time and help.

**Comment by tibbi** [comment]
right, make sense, I moved it to the strings that shouldnt be translated. Thanks
