### ISSUE TITLE
[fr] add a "X" button to the notification

### ISSUE THREAD

**Issue by nameless326** [SimpleMobileTools/Simple-Music-Player#470]
in NewPipe, when you expand the player notification, a new button shows up to close the notification.

here's a comparison, with both collapsed and expanded notifications:

| Simple Music Player | NewPipe |
| --- | --- |
| ![screenshot_20221110-145631](https://user-images.githubusercontent.com/85243826/201176239-e9919997-574f-4f54-bfca-dbb6c6254406.png) | ![screenshot_20221110-145916](https://user-images.githubusercontent.com/85243826/201176287-e75a428d-5017-4db8-938d-c7da79721e8d.png) |
| ![screenshot_20221110-145638](https://user-images.githubusercontent.com/85243826/201176338-426c19e3-1968-49b8-8642-a28b8a1e4d93.png) | ![screenshot_20221110-145923](https://user-images.githubusercontent.com/85243826/201176375-41a85a99-c816-4b9c-823a-d71d7385d210.png) |

I think it would be great to have something similar in your player.

you would see it only if you expand the notification, though.

btw... I don't know if you want me to create a new issue for this, but there should be a setting to disable the preview of the album -and its colors- on the notification. (and just have it in plan gray/dark like in NewPipe)

**Comment by tibbi** [comment]
what OS version are you using? Those notifications changed quite a bit on Android 13 and so I dont want to mess with the previous versions. Forcing colorless notifications isnt really on the roadmap now.

**Comment by nameless326** [comment]
I'm using Android 9.

**Comment by nameless326** [comment]
swiping to the left (or right) to close the notification is really buggy and never really works... that's why I made that suggestion instead.

a simple "X" button would fix that.

**Comment by nameless326** [comment]
can you please reconsider it?

**Comment by tibbi** [comment]
we are rechecking some notification and playback related things, it is really messed up at system level

**Comment by nameless326** [comment]
well... in NewPipe, the "X" button is actually the only method to close the player notification:

https://user-images.githubusercontent.com/85243826/201493841-c53b52b6-eb8c-4c96-89c4-cd06f835eb46.mp4

the notification in NewPipe is not designed to be closed with the swipe gesture.

so, perhaps that would be the solution here? get rid of the swipe gesture and then follow a design similar to Newpipe?

**Comment by nameless326** [comment]
that would indirectly fix the notification...

**Comment by nameless326** [comment]
the player notification is messed up again, it can't be closed no matter what you do.

do you even use your own app?

**Comment by tibbi** [comment]
has been added already
