### ISSUE TITLE
Sort playlists by name

### ISSUE THREAD

**Issue by MaxsimLionel** [SimpleMobileTools/Simple-Music-Player#477]
Give an option in settings or an option at the top of the playlists view on how to sort the playlist page when adding a song to the playlist. Right now there is a "Sort By" function on the playlist overview. I think it would be nice to have similar functionality on the screen that comes up when adding to a playlist. Right now it seems to be sorted by date of playlist creation, which is nice sometimes, especially if it were reversed. Anyway, more options here would be nice. Thank you.

**Comment by tibbi** [comment]
which screen you mean?

**Comment by MaxsimLionel** [comment]
On the screen where the playlists are in order from oldest to newest created. The screen that pops up when you tap "add to playlist".

**Comment by tibbi** [comment]
right, Ill reuse the same sorting at the dialog

**Comment by MaxsimLionel** [comment]
Thanks!
