### ISSUE TITLE
Music Playing in BT headset. Incoming call receives. Call end. Music sound will not come from either speaker or Bluetooth. You have to restart the phone or application in this scenario.

### ISSUE THREAD

**Issue by raihanbinhaniftech** [SimpleMobileTools/Simple-Music-Player#495]
I thinks its a focus problem which is not handled in this Music Application as when the call arrives telephony get the audio stream focus and after the call ends it releases the focus but music app don't get the focus back. So you play the music after the call ends but still the music not giving sound.

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by raihanbinhaniftech** [comment]
Hey Tibbi. Great work I have checked much of your work. I am using the Lineage 18.1 and app version and quite an old app version almost 4 months old.

**Comment by raihanbinhaniftech** [comment]
Sure I have made a lot of changes to it. Can you help me where exactly this was missing the focus issue?

**Comment by tibbi** [comment]
hard to say what was wrong, the whole way of handling audio has been rewritten recently
