### ISSUE TITLE
[Feature request] Save the time position of a file

### ISSUE THREAD

**Issue by mmkamron** [SimpleMobileTools/Simple-Music-Player#508]
Hey, it would be awesome to save the current time position of a file that's let's say longer then 30 minutes (e.g. podcasts) because it doesn't make sense to save the position for a music.

**Comment by tibbi** [comment]
it should be saved already, what app and OS version are you using?

**Comment by mmkamron** [comment]
> it should be saved already, what app and OS version are you using?

OS: Android 10

I checked one more time and it is saving the current position when I quit the app and open again. However, it is not saving it when I switch to another song and back.

**Comment by tibbi** [comment]
well, that isnt even planned. I dont want to save the current position of all tracks
