### ISSUE TITLE
Add file sharing

### ISSUE THREAD

**Issue by Benjamin-Watson0** [SimpleMobileTools/Simple-Music-Player#535]
Note that I am not talking about providing editing tags in the software.
I have been sharing files in the file manager to the tag editor. I think it would be more convenient to share directly in the music player, which can more intuitively see whether the music tag is correct. You don't have to open File Manager>find the music after finding the error. This process is very troublesome.

https://github.com/SimpleMobileTools/Simple-Music-Player/assets/112467275/fb9c3875-b4b8-4963-8fd8-c8c1289dfb51

**Comment by tibbi** [comment]
sharing isnt supposed to be used in these cases, just use Open with
