### ISSUE TITLE
change directory view layout to more "Treeish"

### ISSUE THREAD

**Issue by jlmxyz** [SimpleMobileTools/Simple-Music-Player#543]
Hi, thanks for providing one of the few music player that don't rely on id3tags !

can you provide a (option?) to display directories in more "organized" way?  I usually sort my music library (for exemple a rock folder for rock bands...) 

at this time for example
/emulated/storage/0/music/rock/band1/Album/CD1
/emulated/storage/0/music/rock/band1/Album/CD2
/emulated/storage/0/music/rock/band2/...
/emulated/storage/0/music/rock/band3/Album/CD1
/emulated/storage/0/music/rock/band3/Album/CD2
/emulated/storage/0/music/pop/bandZ/...

are displayed 
CD1
CD2
band2
CD1
CD2
bandz

not friendly right? how to know what is CD1? imagine when there is 10th of multicd albums.... and anyway when you search for a specific album you have to scroll all the directories... 

I would like to have a more "directory tree" behavior :
screen 1 display "rock" and "pop"
if user select "rock" screen display now "band1" "band2" "band3" 
if user select "band3" screen now display "Album" (no "smart enter")
if user select "Album"'screen now display "CD1" and "CD2"

on each screen must be displayed : 
- a "up" button that allow to go up into the tree
- the current path

the path must be "scrollable" so that user can see where the file are stored (for example emulated storage or sdcard) 

thanks and regards

**Comment by tibbi** [comment]
that isnt really on the roadmap now
