### ISSUE TITLE
current playlist : display (!) button at right of music entry to get some information

### ISSUE THREAD

**Issue by jlmxyz** [SimpleMobileTools/Simple-Music-Player#544]
information must at least contain the full scrollable path of the file
additional id3 tag could be added, file size, bitrate... as ffprobe do in linux
thanks and regards

**Comment by tibbi** [comment]
you can already see file properties by long pressing it and using the top Menu -> Properties

**Comment by jlmxyz** [comment]
you're a "litlle" bit fast to close tickets....
as you might have noticed in the title : **current playlist**
eg the playlist at this time playing.... long pressing only provide (-), trashbin, select all, ... , and in ... only add to playlist... where is the (!) that you can find on other screen (playlist screen, folder, artist, albums, tracks?????

**Comment by tibbi** [comment]
what path you want to see at a playlist? It consists of multiple files

**Comment by jlmxyz** [comment]
when I select a file, the (i) icon must be displayed on top, pressing the (i) icon display associated file information, in case of multiple selection the (i) icon shall not be displayed

-------- Message d'origine --------

**Comment by tibbi** [comment]
why not... It works as expected

**Comment by jlmxyz** [comment]
nice :)

------- Original Message -------

**Comment by jlmxyz** [comment]
by the way, it could be nice to add the (i) button on the play screen (where the cover is displayed) so that info about the current song can be found fast and easy!

------- Original Message -------
