### ISSUE TITLE
Skip and playback is triggered by BT disconnect, other media playback or alarm

### ISSUE THREAD

**Issue by tearoww** [SimpleMobileTools/Simple-Music-Player#560]
**Device:** Samsung SM-G970F/DS (Galaxy S10e)
**App version:** 5.16.5 or newer (F-Droid)
**Android version:** 12

**Bug description:**
After playback has stopped and the next song is paused and ready to play, disconnecting a Bluetooth device, activating the microphone in another app, playing media in another app or even getting a silent alarm will start playback. None of this triggers playback on version 5.16.4.

If you need any other information, please ask and I will provide it.

**Comment by tearoww** [comment]
Activating the microphone in an app that doesn't play any sound with the activation does not trigger playback. Thus the activation sound may have counted as playing media, which triggers the playback.

**Comment by naveensingh** [comment]
Hi!

> ...After playback has stopped and the next song is paused and ready to play, disconnecting a Bluetooth device, activating the microphone in another app, playing media in another app or even getting a silent alarm will start playback...

Can you please rephrase these steps? What do you mean by activating the microphone? Do you mean you started a voice recorder?

Are you using "Stop after current playback" mode? If yes, does this issue occur even if you pause playback manually?

> playing media in another app

Does Simple Music Player just take over the audio focus from the other media app you started playback in (i.e. causes the other app to pause)?

**Comment by tearoww** [comment]
Hi!

Let me first add a new detail that I discovered. Simple Music Player **skips to the second song** it would play next and starts playback on that one instead of the one shown on screen before this issue occurs.

Now to answer @naveensingh's questions:

> Can you please rephrase these steps? What do you mean by activating the microphone? Do you mean you started a voice recorder?

Certainly. As my previous comment clarified, some apps (e.g. Babbel or Firefox's search) play a confirmation sound when they start using the device's microphone and it appears that this confirmation sound also caused this issue to occur, not the actual activation of the microphone.

Steps again for clarification:

1. Let Simple Music Player stop playback after the last song on an album
2. Disconnect a Bluetooth device, play media in another app or have an alarm trigger
3. Simple Music Player skips to the next song and starts playback, taking over audio focus

> Are you using "Stop after current playback" mode? If yes, does this issue occur even if you pause playback manually?

I am not using repeat at all ("Repeat off" mode). The issue does not occur if I pause playback manually. It only occurs after Simple Music Player has finished playing the last song of the album, which is my normal use case.

> Does Simple Music Player just take over the audio focus from the other media app you started playback in (i.e. causes the other app to pause)?

Yes, Simple Music Player takes over audio focus and pauses the other application's audio/video playback.

**Comment by naveensingh** [comment]
@tearoww thanks for the details instructions, I was able to reproduce this now :D
