### ISSUE TITLE
Allow to manually edit path of exclude list entries

### ISSUE THREAD

**Issue by d-a-s** [SimpleMobileTools/Simple-Music-Player#586]
All of my system notification sounds were showing up in the play list. They are in nested subfolders, so I had to exclude each one separately:
```
Internal/Android/mdeia/com.google.android.gm/Notifications/Tones/
Internal/Android/mdeia/com.google.android.gm/Notifications/Welcome/
Internal/Android/mdeia/com.google.android.gm/Notifications/Treasure/
...
```
It would be really helpful if there was an "edit" option on the `Manage excluded folders` page. That would have allowed me to make one exclude, then edit it to exclude all of `Internal/Android/mdeia/com.google.android.gm/Notifications/`, rather than having to scroll through and add about 20 separate excludes.

**Comment by tibbi** [comment]
right, you cannot search that, But you can select many folders quickly and use Exclude there.

**Comment by d-a-s** [comment]
In case anyone else finds this, I found a way to exclude all these at once.

I copied a small sound file using the file manager, to the `Android/media` folder. Then when `media` showed up in the music folders list, I was able to exclude just that one folder, and then all the other subfolders disappeared as well.

Thanks tibbi, your comments helped me think of this solution :-)
