### ISSUE TITLE
Play next does not work when gapless playback is on

### ISSUE THREAD

**Issue by brandsimon** [SimpleMobileTools/Simple-Music-Player#590]
When gapless playback is on and I want add a song and play it next (play next button), it is skipped.
Probably the gapless play is calculated in at advanced?

**Comment by tibbi** [comment]
@naveensingh check it please, if you can still reproduce it

**Comment by naveensingh** [comment]
Yes, I can reproduce it on master but not on my media3 branch. (I didn't notice that the next track player in service should be updated when reviewing that play next PR, probably why this happened)

**Comment by tibbi** [comment]
alright, so it will be fixed in the next app version released soon
