### ISSUE TITLE
Feature request: dont delete current queue when pressing on a song

### ISSUE THREAD

**Issue by brandsimon** [SimpleMobileTools/Simple-Music-Player#591]
Sometimes I put a lot of tracks into the queue and then accidentally press on a track, which plays the song and deletes the queue. This is annoying, because the work is lost.

I see two solutions:
- Ask before deleting the playlist, which is probably annoying if somebody uses the current behavior a lot
- Make the default action (when pressing on a song) configurable (play, enqueue). This does not break somebody's use-case.

**Comment by tibbi** [comment]
that isnt really on the roadmap

**Comment by brandsimon** [comment]
@tibbi 
Is there another solution to solve my problem? (Like restore the deleted queue or anything else?)

**Comment by tibbi** [comment]
not really, Im not aware of any
