### ISSUE TITLE
Not opening in Oneplus3

### ISSUE THREAD

**Issue by Ludvins** [SimpleMobileTools/Simple-Music-Player#60]

**Comment by tibbi** [comment]
were you using the previous version, it broke just after the update?

**Comment by Ludvins** [comment]
Installed yesterday 2.2.1 version from F-droid. Version 2.2.2 is not avaible there.

**Comment by Ludvins** [comment]
Uploaded to 2.2.2 and still not opening.

**Comment by Zykino** [comment]
I also have a OP3 with this app from f-droid 2.2.2 and the app open and run smoothly :s

**Comment by Ludvins** [comment]
It opens now, don't know the reason.
