### ISSUE TITLE
Start choice of playlists from widgit

### ISSUE THREAD

**Issue by Noitarud** [SimpleMobileTools/Simple-Music-Player#601]
I have to install multiple music player apps to get this and I just want it in just one player.
I have these widgets:
• Teachings in VLC
• Music in yours
• Brown noise in Metro
I can press play on one and it begins that playlist.

I have decided to ask you first*, I would like extra buttons for favourite playlists to trigger them at will from the widget. Perhaps allow user to draw for the icon or choose from a selection of predrawn.

*though yor player doesn't repeat the brownnoise track very seamlessly (none do it great)

**Comment by tibbi** [comment]
that will be added as a shortcut in the future

**Comment by Noitarud** [comment]
I get the feeling the "shortcut" will not be what I was saying.
I was hoping the widget would be enlarged with buttons to immediately play/resume whatever playlist amoung the ones I have opted to have on it. This actually was the reason I got your app - to resume one more playlist. This is cluttering my home screen.
