### ISSUE TITLE
no option to add folder in `Settings > Manage excluded folders`

### ISSUE THREAD

**Issue by foss-** [SimpleMobileTools/Simple-Music-Player#618]
Can't seem to add folders to the exclusion list in `Settings > Manage excluded folders`:

<img src="https://github.com/SimpleMobileTools/Simple-Music-Player/assets/5708172/373caa38-3d2d-4593-88ee-9ff0eea3b65f" width="450">

https://github.com/SimpleMobileTools/Simple-Music-Player/issues/248 states "The app will be slowly moving towards relying on the MediaStore, it will eventually lose File access altogether. It simply wont know which file is stored in what folder."

Does that mean the setting in question is no longer functional? Should it be removed?

**Comment by tibbi** [comment]
you can exclude folders from the Folders tab on the main screen

**Comment by foss-** [comment]
Wouldn't you agree that adding an exclude option to the exclude view would be a good idea? After all it is called `Manage excluded folders`. I understand the exclusion supposedly happens elsewhere but the concept is not easily conveyed to users in the current form.

**Comment by tibbi** [comment]
sadly this app cannot browse folders freely due to insufficient permissions

**Comment by foss-** [comment]
Thanks for elaborating. Requesting the required permissions would not be an option?

**Comment by tibbi** [comment]
apps like this are not allowed to do it anymore

**Comment by ace280** [comment]
Would it be possible to highlight in the folder overview, which of those folders are already excluded?
