### ISSUE TITLE
Media buttons are ignored

### ISSUE THREAD

**Issue by Zykino** [SimpleMobileTools/Simple-Music-Player#64]
From my comments on #17:
> [...] I cannot use my OnePlus 3 gestures to Play/Pause or use next/previous track. I'm use to draw || or < or > on my screen without looking at it and this app doesn't register the commands.

I think Android what's missing is the integration of media buttons: https://developer.android.com/guide/topics/media-apps/mediabuttons.html

**Comment by carloshs94** [comment]
Hi @tibbi is this still working?
cant get any response while pressing media buttons on the headset.
i've tried with google play music & spotify and it works, so its not my headphone. (Android 9)

**Comment by tibbi** [comment]
@carloshs94 if I send you a test version with some debug messages at button press appearing, can you try it? If you can, shoot me a mail at hello@simplemobiletools.com, it is easier to communicate and send files there. Thanks

**Comment by carloshs94** [comment]
sure, ill send you an email

**Comment by tibbi** [comment]
should be working in 5.1.0 released soon
