### ISSUE TITLE
Feature request - Seasonal directory switch.

### ISSUE THREAD

**Issue by antrys** [SimpleMobileTools/Simple-Music-Player#73]
I know of zero music players that do this, and I've looked for 20 years now.  It seems very simple to implement and I figured the worst I could do is ask. I'd dang near kill for this.

Come Christmas-time, I listen to a whole other set of music, it's a large collection, way to big to manage with a playlist or to edit every id3 tag.  I just put it all in another directory.  But I've never seen a player that will just let me switch what directory it uses, in the UI.  The closest I've come is using .nomedia files with google play. But If I decide to switch libraries while driving or working, forget it.  It'd be nice to have an A/B switch to pick what root directory of the music I want.    (Every other player wants me to listen to "O Come all ye Faithful" on August 3rd...)

**Comment by tibbi** [comment]
Im not entirely sure what you mean. How is it different from a playlist per folder?

**Comment by antrys** [comment]
Because it's many subfolders. But it's all one "theme" that only gets listened to one month out of the year.
`Seasonal music/Artist/album1
                          |        |/Album2
                          /Artist2/album1`
But each album, sometimes each song on each album has nothing to correspond it with other songs in this "Mega category".  I'd have to update the playlist every time I added a new album.  I've currently got about 20 days worth of music in this category.  It'd be very hard to maintain.  I'd rather have it played at the file-level than playlist level.

**Comment by tibbi** [comment]
Aha, I dont think I want to implement such feature either, it's just not many people needing something so advanced. Simple switching between playlists is my way to go. Sorry

**Comment by antrys** [comment]
Yup. Like I said. Nobody in 20 yeas has wanted to do it.

**Comment by MaxsimLionel** [comment]
> Yup. Like I said. Nobody in 20 yeas has wanted to do it.

Maybe try Classical Music Tagger on F-droid. You can tags many files at the same time.
