### ISSUE TITLE
Neither files nor folders can be added to playlists

### ISSUE THREAD

**Issue by Zero3** [SimpleMobileTools/Simple-Music-Player#75]
I just downloaded the app from Google Play, but am unable to add files or folders to a playlist. After selecting a file/folder, the app simply returns to the main view. When selecting a folder, I tried both a folder containing many media files as well as the global Downloads folder containing just a single .mp3 file. A toast message saying "Fetching songs..." appears at the bottom, but nothing happens no matter how long I wait.

The only way I managed to play a music file is by opening it through another app and selecting Simple Music Player as the player.

I'm running Android 8.0.0 on a Google Nexus 6P.

**Comment by tibbi** [comment]
The app is quite primitive currently. Are you sure the file or folder is not added to the current playlist? There's no new playlist created automatically, not even if you include a whole folder.

**Comment by Zero3** [comment]
@tibbi I guess so? The main screen keeps saying "Your playlist is empty". Clicking play results in an error toast message saying "Current playlist is empty".

**Comment by tibbi** [comment]
Aha :) The Music player needs a lot more work, I will get there someday.

**Comment by tibbi** [comment]
something related has just been fixed, so I guess this will work properly in 3.1.0 released soon.
