### ISSUE TITLE
Suddenly Low volume

### ISSUE THREAD

**Issue by daniel-wtd** [SimpleMobileTools/Simple-Music-Player#78]
Hey,

found your app recently. Very nice. Unfortunately it is having a very weird issue. 

Reproduce:
Start music
Start another App, which uses Sound (ex.: Realm Defense ).
Play a little.
Suddenly Volume of music ist very Low and will not recover.

Force killing the player will recover the original Volume.

Hope you can fiddle it out. If more information are needed, please feel free to notify me.

**Comment by tibbi** [comment]
Hey, Ive just done some changes related to audio focus gain/loss so if you start the game, the music will stop. You can easily resume the song through the music player notification if you wish so. It will be fixed in 3.1.0, reopen the issue if it still messes with the volume. Thanks

**Comment by daniel-wtd** [comment]
I'll try this out. thanks a lot!
