### ISSUE TITLE
A bit too simple

### ISSUE THREAD

**Issue by goldencut** [SimpleMobileTools/Simple-Music-Player#8]
Nice clean UI. But. I have 100s, maybe 1000s of audio files on my phone. Some of them are audiobooks, with 10s (100s) of chapters. Presenting them all alphabetically, mixed together (music+audiobook chapters), as one long list just won't cut it. Needs: 
1)folder view (tapping on folder 'enters' it listing files in there), plays files in this list
Less critical:
2)repeat track, repeat list (folder)
3)headphones button support
4)playlist(s)

Thnx

**Comment by tibbi** [comment]
Yeah, I will have to do something about those filters and picking songs. What headphone buttons don't work to you? Those are supposed to be ok as well as changing the volume through the headphone.
parent of #6

**Comment by goldencut** [comment]
Simple single button earplugs, and apparently it was remedied by rebooting the phone. So button works, although somewhat erraticly - sometimes button press won't register, sometimes Google app gets triggered. But this might be the cheap earplugs or the phone (Honor 6C). After install also the notification controls wouldn't work but reboot remedied that also.
I'd prefer folder view to complex filters and multiple tabs since not all my music is correctly tagged, and my music is organized already anyway - in folders. 

Thnx

**Comment by tibbi** [comment]
so Ive already got headphones with volume buttons too, but I just cant seem to make it work.. Apparently other apps arent reacting to them either, so I guess the issue will be with the headset.

**Comment by Rbagman** [comment]
Yes. Mine (came with the device) work great with the stock player, but I get mixed results with other players.

**Comment by tibbi** [comment]
many of these things have already been fixed, report the remaining issues one by one in case you are still around
