### ISSUE TITLE
The application won't stop playing played music even if there is another media files that will be played in another application

### ISSUE THREAD

**Issue by philiparniebinag** [SimpleMobileTools/Simple-Music-Player#87]
This article is for **"Simple Music Player"** which may fall in the category of ***Bug Hunting***.

As stated in the title of this article, the application **won't stop playing played music even if there is another media files will be played in another application.**

I consider this a bug as I rarely see media player application that will never stop playing if there are another media files that will be played in another application.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514369070/z2lisc0kptmxrescnkpa.png)

In the picture above with the highlighted box, it is the notification for **Simple Music Player** which is playing *The Spectre* of *Alan Walker* continuously together with the  *Bailando* of *Enrique Iglesias*.

Normally, some application will stop playing if another media files will be played from other application but not it **Simple Music Player**.

### More details about this article
To understand it better, I documented this article for the better details. More information will be found on the video.

https://youtu.be/n6i363BNijY

That's all.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@philiparniebinag/the-application-won-t-stop-playing-played-music-even-if-there-is-another-media-files-will-be-played-in-another-application">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by madmirstman** [comment]
Background playback is useful feature , not a bug . 
Option to turn off background playback would also be useful feature , but background playpack should **not** be removed .

**Comment by philiparniebinag** [comment]
My apologizes for calling it a bug sir madmirstman. I will correct my mistakes by providing another details and I will post another article about this. I made some recent suggestion for the application and I enjoy using it.

Thank you so much sir for responding my article.

I will promote Simple Music Player by making article again about it. The thing is, I like using the app.

Sent from Mail for Windows 10

**Comment by tibbi** [comment]
I just actually made the song stop if the app loses focus as I think it is the expected behaviour and most apps I tested do that. If you want to keep the song playing, just press Play at the music player notification. I dont really want to add a setting for it, lets see what will the users tell. Thanks
