### ISSUE TITLE
Widget vertical padding

### ISSUE THREAD

**Issue by Noino** [SimpleMobileTools/Simple-Music-Player#89]
The music player widget has some serious vertical padding which makes it really hard to fit on my home screen. I use nova launcher, but i tried it on touchwiz as well and on both i have to make the widget much too high before the now playing part becomes visible. With nova the only mode in which there is no wasted space is when i make it as slim as possible and only view the music controls, on touchwiz i cant even do that, and there is always blank space above and below the widget.

I believe it would be proper for the widget to expand in to its two line mode as soon as it can fit within its box, with no blank space at all, and possibly to even add another line for now playing if there is sufficient space for it.

![smp_widget](https://user-images.githubusercontent.com/504736/34867169-daaa7344-f787-11e7-9361-32099c39361f.jpg)
![smp_widget2](https://user-images.githubusercontent.com/504736/34867170-dad8944a-f787-11e7-98c1-716f2af8c2c3.jpg)

**Comment by tibbi** [comment]
it expands properly on all my test devices, nobody reported such issue yet. Other app widgets work fine? If you press play or change the song it doesnt fix itself?

**Comment by Noino** [comment]
Pressing buttons has no effect. I basically need double height for the now playing expansion to happen.
Other widgets work mostly fine. The stock alarm clock widget doesn't text wrap quite as it should on Nova launcher, but works fine with samsungs own touchwiz. Otherwise no problems.
I'm running a unrooted S7 if that helps at all

**Comment by GuitarBilly** [comment]
Exact the same issue here. 
By default the widget has more padding above and below the content then the height of the 2 content lines. When i reduce the height of the widget the content gets cropped from 2 lines to 1 line. Other app widgets like VLC player or Simple Clock do not show this behavior.

Luckily i have a big FHD screen so i just give it half the screen.

Nokia6 on Android 7.1.2.
Simple Music Player v3.2.5

**Comment by tibbi** [comment]
the way widget type is selected will be changed in 4.0, just recreating the widget should be all you have to do. Ill close this, reopen if still broken somehow.
